name = "Graphon"
version = "0.1.0"
defaultTargets = ["Graphon"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "d557daf6dc764277d2f5cb03daf31d21bc5f01d3"

[[lean_lib]]
name = "Graphon"
