/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Mathlib.Probability.Independence.Conditional
import Graphon.ForMathlib.CompProdComap

/-!
# Relatively independent joinings over a common factor

Given two probability spaces carrying a *common factor* — measurable maps `q : Ω → Z` and
`r : Ξ → Z` with the same pushforward — this file builds the canonical coupling of `μ` and `ν`
that identifies the two factors and adds nothing else:

`relativeFactorCoupling μ ν q r = (condDistrib id q μ ×ₖ condDistrib id r ν) ∘ₘ μ.map q`

Both sides are disintegrated over `Z` and the fibres are then multiplied independently. Nothing
else would do: the independent product `μ.prod ν` does not satisfy `q X = r Ξ`, and an arbitrary
coupling with that identity could still let each side see more of the other than the common
factor does.

## Main results

* `map_condDistrib_id` — **fibre concentration**: the conditional law of a point given its factor
  value, pushed forward through the factor, is the deterministic identity kernel. This is the
  whole content of "conditioning on `q` pins down `q`", and everything below rests on it.
* `map_fst_relativeFactorCoupling`, `map_snd_relativeFactorCoupling` — the two marginals are `μ`
  and `ν` (the second under the standing hypothesis `ν.map r = μ.map q`).
* `comp_fst_ae_eq_comp_snd_relativeFactorCoupling` — the **common-factor identity**
  `q ∘ Prod.fst =ᵐ r ∘ Prod.snd`.
* `condIndepFun_fst_snd_relativeFactorCoupling` — the two coordinates are conditionally
  independent **given the common factor read off the first coordinate**.
* `condDistrib_id_map_comap` — **fibre transport**: a measure-preserving `T` shifting the factor
  by `e` carries the disintegration kernel along, so conditioning at `z` and pushing through `T`
  is conditioning at `e z`.
* `map_prodMap_relativeFactorCoupling_two_sided` — hence a pair of measure-preserving maps
  shifting the two factors by one and the same `e` gives a symmetry of the joining. The
  pushforward identity on the factor law is derived from the commuting square, not assumed, and
  `MeasurableEmbedding e` suffices: injectivity is what cancels the pushforward, surjectivity is
  never used.
* `map_prodMap_relativeFactorCoupling` — the degenerate case `e = id`, `U = id`, retained because
  it avoids `hr`, `hqr` and the second map, which makes it the better API where the factor is
  literally fixed.
* `condIndepFun_comp_fst_snd_relativeFactorCoupling` — the transfer clause.

## Why condition on `q ∘ Prod.fst`

The conditioning σ-algebra is `MeasurableSpace.comap (q ∘ Prod.fst) inferInstance`, generated by a
genuine random variable on the coupling space, not by an auxiliary `Z`-valued variable that the
composition `∘ₘ` has integrated out. Only the former is available to downstream consumers, who see
the coupling and not its construction. The common-factor identity above transfers the statement to
`r ∘ Prod.snd` whenever that is the more convenient side.

Note that the coupling gives only `σ(q ∘ fst) ⊆ σ(snd)` modulo the law: the second coordinate may
carry strictly more information than the shared factor, exactly as a uniform `U` carries more than
`1_{U < p}`. What the conditional independence excludes is that the surplus says anything about
the first coordinate beyond what the factor already determines.
-/

open MeasureTheory ProbabilityTheory

namespace ProbabilityTheory

variable {Ω Ξ Z : Type*} [MeasurableSpace Ω] [StandardBorelSpace Ω] [Nonempty Ω]
  [MeasurableSpace Ξ] [StandardBorelSpace Ξ] [Nonempty Ξ]
  [MeasurableSpace Z] [StandardBorelSpace Z] [Nonempty Z]

/-! ### Fibre concentration -/

/-- **Fibre concentration.** The conditional law of a point given the value of a factor map is
carried by the fibre over that value: pushing `condDistrib id q μ` forward through `q` returns
the deterministic identity kernel, almost everywhere for the law of the factor. -/
theorem map_condDistrib_id (μ : Measure Ω) [IsFiniteMeasure μ] {q : Ω → Z} (hq : Measurable q) :
    (condDistrib id q μ).map q =ᵐ[μ.map q] Kernel.id := by
  have h₁ : condDistrib (q ∘ (id : Ω → Ω)) q μ =ᵐ[μ.map q] (condDistrib id q μ).map q :=
    condDistrib_comp q aemeasurable_id hq
  have h₂ : condDistrib q q μ =ᵐ[μ.map q] Kernel.id := condDistrib_self q
  have h₃ : condDistrib q q μ =ᵐ[μ.map q] (condDistrib id q μ).map q := by simpa using h₁
  exact h₃.symm.trans h₂

/-- The fibre over `z` carries all of the conditional law given `z`. -/
theorem condDistrib_id_apply_fibre (μ : Measure Ω) [IsFiniteMeasure μ] {q : Ω → Z}
    (hq : Measurable q) :
    ∀ᵐ z ∂(μ.map q), (condDistrib id q μ) z (q ⁻¹' {z}) = 1 := by
  filter_upwards [map_condDistrib_id μ hq] with z hz
  rw [← Measure.map_apply hq (measurableSet_singleton z), ← Kernel.map_apply _ hq, hz,
    Kernel.id_apply]
  simp

/-- Pointwise form of fibre concentration: conditionally on the factor value `z`, the factor is
almost surely equal to `z`. -/
theorem ae_ae_eq_condDistrib_id (μ : Measure Ω) [IsFiniteMeasure μ] {q : Ω → Z}
    (hq : Measurable q) :
    ∀ᵐ z ∂(μ.map q), ∀ᵐ x ∂(condDistrib id q μ) z, q x = z := by
  filter_upwards [condDistrib_id_apply_fibre μ hq] with z hz
  rw [ae_iff, show {x | ¬ q x = z} = (q ⁻¹' {z})ᶜ from by ext x; simp]
  exact (prob_compl_eq_zero_iff (hq (measurableSet_singleton z))).mpr hz

/-! ### The coupling -/

/-- **The relatively independent joining of `μ` and `ν` over their common `Z`-factor.** Both sides
are disintegrated over `Z` — `μ` along `q`, `ν` along `r` — and the fibres are then multiplied
independently. -/
noncomputable def relativeFactorCoupling (μ : Measure Ω) (ν : Measure Ξ) [IsFiniteMeasure μ]
    [IsFiniteMeasure ν] (q : Ω → Z) (r : Ξ → Z) : Measure (Ω × Ξ) :=
  ((condDistrib id q μ) ×ₖ (condDistrib id r ν)) ∘ₘ (μ.map q)

instance instIsFiniteMeasureRelativeFactorCoupling (μ : Measure Ω) (ν : Measure Ξ)
    [IsFiniteMeasure μ] [IsFiniteMeasure ν] (q : Ω → Z) (r : Ξ → Z) :
    IsFiniteMeasure (relativeFactorCoupling μ ν q r) := by
  haveI : IsFiniteMeasure (μ.map q) := Measure.isFiniteMeasure_map μ q
  rw [relativeFactorCoupling]
  infer_instance

variable {μ : Measure Ω} {ν : Measure Ξ} [IsProbabilityMeasure μ] [IsProbabilityMeasure ν]
  {q : Ω → Z} {r : Ξ → Z}

omit [StandardBorelSpace Z] [Nonempty Z] in
/-- The coupling is a probability measure. Measurability of `q` is genuinely needed: without it
`μ.map q` is the zero measure. -/
theorem isProbabilityMeasure_relativeFactorCoupling (hq : Measurable q) :
    IsProbabilityMeasure (relativeFactorCoupling μ ν q r) := by
  haveI : IsProbabilityMeasure (μ.map q) := Measure.isProbabilityMeasure_map hq.aemeasurable
  rw [relativeFactorCoupling]
  infer_instance

omit [StandardBorelSpace Z] [Nonempty Z] in
/-- The first marginal is `μ`. -/
theorem map_fst_relativeFactorCoupling (hq : Measurable q) :
    (relativeFactorCoupling μ ν q r).map Prod.fst = μ := by
  rw [relativeFactorCoupling, Measure.map_comp _ _ measurable_fst, ← Kernel.fst_eq, Kernel.fst_prod]
  simpa using condDistrib_comp_map (X := q) hq.aemeasurable (aemeasurable_id (μ := μ))

omit [StandardBorelSpace Z] [Nonempty Z] in
/-- The second marginal is `ν`, under the standing hypothesis that the two factors have the same
law. -/
theorem map_snd_relativeFactorCoupling (hr : Measurable r) (hqr : ν.map r = μ.map q) :
    (relativeFactorCoupling μ ν q r).map Prod.snd = ν := by
  rw [relativeFactorCoupling, Measure.map_comp _ _ measurable_snd, ← Kernel.snd_eq,
    Kernel.snd_prod, ← hqr]
  simpa using condDistrib_comp_map (μ := ν) (X := r) hr.aemeasurable (aemeasurable_id (μ := ν))

/-- **The common-factor identity**: the two coordinates agree on the shared factor. Proved from
the two fibre-concentration statements, one on each side of the joining — equality of the two
factor *marginals* would not suffice, since it says nothing about the joint law. -/
theorem comp_fst_ae_eq_comp_snd_relativeFactorCoupling (hq : Measurable q) (hr : Measurable r)
    (hqr : ν.map r = μ.map q) :
    q ∘ Prod.fst =ᵐ[relativeFactorCoupling μ ν q r] r ∘ Prod.snd := by
  haveI : IsProbabilityMeasure (μ.map q) := Measure.isProbabilityMeasure_map hq.aemeasurable
  have hmeas : MeasurableSet {p : Ω × Ξ | (q ∘ Prod.fst) p = (r ∘ Prod.snd) p} :=
    measurableSet_eq_fun (hq.comp measurable_fst) (hr.comp measurable_snd)
  have hν : ∀ᵐ z ∂(μ.map q), ∀ᵐ y ∂(condDistrib id r ν) z, r y = z := by
    rw [← hqr]; exact ae_ae_eq_condDistrib_id ν hr
  rw [Filter.EventuallyEq, relativeFactorCoupling, Measure.ae_comp_iff hmeas]
  filter_upwards [ae_ae_eq_condDistrib_id μ hq, hν] with z hz hz'
  rw [Kernel.prod_apply]
  have h1 : ∀ᵐ p ∂(((condDistrib id q μ) z).prod ((condDistrib id r ν) z)), q p.1 = z :=
    Measure.quasiMeasurePreserving_fst.ae hz
  have h2 : ∀ᵐ p ∂(((condDistrib id q μ) z).prod ((condDistrib id r ν) z)), r p.2 = z :=
    Measure.quasiMeasurePreserving_snd.ae hz'
  filter_upwards [h1, h2] with p hp1 hp2
  simp only [Function.comp_apply, hp1, hp2]

/-- The joint law of the common factor and the two coordinates: the factor is a.s. the
disintegration variable, so reading it off the first coordinate reconstitutes the outer
integration. This is the structural identity behind the conditional independence below. -/
theorem map_factorProd_relativeFactorCoupling (hq : Measurable q) :
    (relativeFactorCoupling μ ν q r).map (fun p => (q p.1, p.1, p.2))
      = (Kernel.id ×ₖ ((condDistrib id q μ) ×ₖ (condDistrib id r ν))) ∘ₘ (μ.map q) := by
  haveI : IsProbabilityMeasure (μ.map q) := Measure.isProbabilityMeasure_map hq.aemeasurable
  have hw : Measurable (fun p : Ω × Ξ => (q p.1, p.1, p.2)) :=
    (hq.comp measurable_fst).prodMk measurable_id
  rw [relativeFactorCoupling, Measure.map_comp _ _ hw]
  refine Measure.comp_congr ?_
  filter_upwards [ae_ae_eq_condDistrib_id μ hq] with z hz
  rw [Kernel.map_apply _ hw, Kernel.prod_apply, Kernel.prod_apply, Kernel.id_apply,
    Measure.dirac_prod, Kernel.prod_apply]
  refine Measure.map_congr ?_
  have h1 : ∀ᵐ p ∂(((condDistrib id q μ) z).prod ((condDistrib id r ν) z)), q p.1 = z :=
    Measure.quasiMeasurePreserving_fst.ae hz
  filter_upwards [h1] with p hp
  simp [hp]

omit [StandardBorelSpace Z] [Nonempty Z] in
/-- **A symmetry of the first space that fixes the factor is a symmetry of the coupling.** If `T`
preserves `μ` and satisfies `q ∘ T = q`, then `Prod.map T id` preserves the joining: `T` acts
within the fibres of `q`, so it leaves each disintegration fibre invariant and never touches the
outer integration. -/
theorem map_prodMap_relativeFactorCoupling (hq : Measurable q) {T : Ω → Ω}
    (hT : MeasurePreserving T μ μ) (hqT : q ∘ T = q) :
    (relativeFactorCoupling μ ν q r).map (Prod.map T id) = relativeFactorCoupling μ ν q r := by
  haveI : IsProbabilityMeasure (μ.map q) := Measure.isProbabilityMeasure_map hq.aemeasurable
  have h1 : condDistrib T q μ =ᵐ[μ.map q] (condDistrib id q μ).map T := by
    simpa using condDistrib_comp q aemeasurable_id hT.measurable
  have h2 : condDistrib T q μ =ᵐ[μ.map q] condDistrib id q μ := by
    rw [condDistrib_ae_eq_iff_measure_eq_compProd _ hT.measurable.aemeasurable,
      compProd_map_condDistrib (aemeasurable_id (μ := μ))]
    simp only [id_eq]
    have hcomp : (fun x => (q x, T x)) = (fun y : Ω => (q y, y)) ∘ T := by
      funext x
      have hx : q (T x) = q x := congrFun hqT x
      rw [Function.comp_apply, hx]
    calc μ.map (fun x => (q x, T x))
        = μ.map ((fun y : Ω => (q y, y)) ∘ T) := by rw [hcomp]
      _ = (μ.map T).map (fun y : Ω => (q y, y)) :=
          (Measure.map_map (by fun_prop) hT.measurable).symm
      _ = μ.map (fun y : Ω => (q y, y)) := by rw [hT.map_eq]
  have hcd : (condDistrib id q μ).map T =ᵐ[μ.map q] condDistrib id q μ := h1.symm.trans h2
  rw [relativeFactorCoupling, Measure.map_comp _ _ (hT.measurable.prodMap measurable_id)]
  refine Measure.comp_congr ?_
  filter_upwards [hcd] with z hz
  rw [Kernel.map_apply _ (hT.measurable.prodMap measurable_id), Kernel.prod_apply,
    ← Measure.map_prod_map _ _ hT.measurable measurable_id,
    ← Kernel.map_apply _ hT.measurable, hz, Measure.map_id]

omit [StandardBorelSpace Z] [Nonempty Z] in
/-- **Fibre transport.** If `T` preserves `μ` and shifts the factor by `e`, then the
disintegration kernel is carried along: conditioning at `z` and pushing through `T` is
conditioning at `e z`. -/
theorem condDistrib_id_map_comap (hq : Measurable q) {T : Ω → Ω} {e : Z → Z}
    (he : MeasurableEmbedding e) (hT : MeasurePreserving T μ μ) (hqT : e ∘ q = q ∘ T) :
    (condDistrib id q μ).map T =ᵐ[μ.map q] (condDistrib id q μ).comap e he.measurable := by
  haveI : IsProbabilityMeasure (μ.map q) := Measure.isProbabilityMeasure_map hq.aemeasurable
  have hρ : (μ.map q).map e = μ.map q := by
    rw [Measure.map_map he.measurable hq, hqT, ← Measure.map_map hq hT.measurable, hT.map_eq]
  have h1 : condDistrib T q μ =ᵐ[μ.map q] (condDistrib id q μ).map T := by
    simpa using condDistrib_comp q aemeasurable_id hT.measurable
  have h2 : condDistrib T q μ =ᵐ[μ.map q] (condDistrib id q μ).comap e he.measurable := by
    rw [condDistrib_ae_eq_iff_measure_eq_compProd _ hT.measurable.aemeasurable]
    refine (he.prodMap MeasurableEmbedding.id).map_injective ?_
    rw [Measure.map_prodMap_compProd_comap _ he.measurable, hρ,
      compProd_map_condDistrib (aemeasurable_id (μ := μ)),
      Measure.map_map (he.measurable.prodMap measurable_id) (hq.prodMk hT.measurable)]
    have hcomp : (Prod.map e id) ∘ (fun x => (q x, T x)) = (fun y : Ω => (q y, y)) ∘ T := by
      funext x
      have hx : e (q x) = q (T x) := congrFun hqT x
      simp only [Function.comp_apply, Prod.map_apply, id_eq, hx]
    rw [hcomp, ← Measure.map_map (by fun_prop) hT.measurable, hT.map_eq]
    simp
  exact h1.symm.trans h2

omit [StandardBorelSpace Z] [Nonempty Z] in
/-- **Two-sided transport of the joining.** A pair of measure-preserving maps that shift the two
factors by one and the same `e` gives a symmetry of the coupling.

The pushforward identity `(μ.map q).map e = μ.map q` is *derived* from the commuting square and
measure preservation, not assumed: taking it as a hypothesis would be redundant and would let a
caller supply an inconsistent pair. `MeasurableEmbedding e` is what the uniqueness step needs —
it cancels a pushforward along `Prod.map e id` — and surjectivity is never used. -/
theorem map_prodMap_relativeFactorCoupling_two_sided (hq : Measurable q) (hr : Measurable r)
    (hqr : ν.map r = μ.map q) {T : Ω → Ω} {U : Ξ → Ξ} {e : Z → Z} (he : MeasurableEmbedding e)
    (hT : MeasurePreserving T μ μ) (hU : MeasurePreserving U ν ν)
    (hqT : e ∘ q = q ∘ T) (hrU : e ∘ r = r ∘ U) :
    (relativeFactorCoupling μ ν q r).map (Prod.map T U) = relativeFactorCoupling μ ν q r := by
  haveI : IsProbabilityMeasure (μ.map q) := Measure.isProbabilityMeasure_map hq.aemeasurable
  have hρ : (μ.map q).map e = μ.map q := by
    rw [Measure.map_map he.measurable hq, hqT, ← Measure.map_map hq hT.measurable, hT.map_eq]
  have hκ := condDistrib_id_map_comap hq he hT hqT
  have hη : (condDistrib id r ν).map U =ᵐ[μ.map q] (condDistrib id r ν).comap e he.measurable := by
    rw [← hqr]; exact condDistrib_id_map_comap hr he hU hrU
  rw [relativeFactorCoupling, Measure.map_comp _ _ (hT.measurable.prodMap hU.measurable)]
  have hstep : ((condDistrib id q μ ×ₖ condDistrib id r ν).map (Prod.map T U)) ∘ₘ (μ.map q) =
      ((condDistrib id q μ ×ₖ condDistrib id r ν).comap e he.measurable) ∘ₘ (μ.map q) := by
    refine Measure.comp_congr ?_
    filter_upwards [hκ, hη] with z hz hz'
    rw [Kernel.map_apply _ (hT.measurable.prodMap hU.measurable), Kernel.prod_apply,
      ← Measure.map_prod_map _ _ hT.measurable hU.measurable,
      ← Kernel.map_apply _ hT.measurable, ← Kernel.map_apply _ hU.measurable, hz, hz',
      Kernel.comap_apply, Kernel.comap_apply, Kernel.comap_apply, Kernel.prod_apply]
  rw [hstep, Measure.comp_comap _ he.measurable, hρ]

/-- **The two coordinates are conditionally independent given the common factor.** The
conditioning σ-algebra is the one generated by `q ∘ Prod.fst`, a random variable on the coupling
space itself rather than the integrated-out disintegration variable. -/
theorem condIndepFun_fst_snd_relativeFactorCoupling (hq : Measurable q) (hr : Measurable r)
    (hqr : ν.map r = μ.map q) :
    CondIndepFun (MeasurableSpace.comap (q ∘ Prod.fst) inferInstance)
      (hq.comp measurable_fst).comap_le Prod.fst Prod.snd (relativeFactorCoupling μ ν q r) := by
  haveI : IsProbabilityMeasure (μ.map q) := Measure.isProbabilityMeasure_map hq.aemeasurable
  set P := relativeFactorCoupling μ ν q r with hP
  -- the law of the common factor on the coupling space
  have hmapk : P.map (q ∘ Prod.fst) = μ.map q := by
    rw [hP, ← Measure.map_map hq measurable_fst, map_fst_relativeFactorCoupling hq]
  -- the two conditional distributions are the two disintegration kernels
  have hcd1 : condDistrib Prod.fst (q ∘ Prod.fst) P =ᵐ[μ.map q] condDistrib id q μ := by
    rw [← hmapk, condDistrib_ae_eq_iff_measure_eq_compProd _ measurable_fst.aemeasurable, hmapk,
      compProd_map_condDistrib (aemeasurable_id (μ := μ))]
    rw [show (fun p : Ω × Ξ => ((q ∘ Prod.fst) p, p.1)) = (fun x : Ω => (q x, id x)) ∘ Prod.fst from
      rfl, ← Measure.map_map (by fun_prop) measurable_fst, hP,
      map_fst_relativeFactorCoupling hq]
  have hcd2 : condDistrib Prod.snd (q ∘ Prod.fst) P =ᵐ[μ.map q] condDistrib id r ν := by
    rw [← hmapk, condDistrib_ae_eq_iff_measure_eq_compProd _ measurable_snd.aemeasurable, hmapk,
      ← hqr, compProd_map_condDistrib (aemeasurable_id (μ := ν))]
    have hswap : P.map (fun p : Ω × Ξ => ((q ∘ Prod.fst) p, p.2))
        = P.map (fun p : Ω × Ξ => (r p.2, id p.2)) := by
      refine Measure.map_congr ?_
      filter_upwards [comp_fst_ae_eq_comp_snd_relativeFactorCoupling hq hr hqr] with p hp
      rw [show ((q ∘ Prod.fst) p, p.2) = ((r ∘ Prod.snd) p, p.2) from by rw [hp]]
      rfl
    rw [hswap, show (fun p : Ω × Ξ => (r p.2, id p.2)) = (fun y : Ξ => (r y, id y)) ∘ Prod.snd from
      rfl, ← Measure.map_map (by fun_prop) measurable_snd, hP,
      map_snd_relativeFactorCoupling hr hqr]
  rw [condIndepFun_iff_map_prod_eq_prod_condDistrib_prod_condDistrib measurable_fst measurable_snd
    (hq.comp measurable_fst), hmapk]
  simp only [Function.comp_apply]
  rw [map_factorProd_relativeFactorCoupling hq]
  refine (Measure.comp_congr ?_).symm
  filter_upwards [hcd1, hcd2] with z h1 h2
  rw [Kernel.prod_apply, Kernel.prod_apply, Kernel.prod_apply, Kernel.prod_apply, h1, h2]

/-- **The transfer clause.** Conditional independence passes to any measurable function of the
first coordinate: the second coordinate tells nothing about *any* reading of the first beyond
what the common factor already determines. Stated separately because this — not the marginals and
not the common-factor identity — is what rules out the second coordinate secretly encoding the
part of the first that the factor leaves unresolved. -/
theorem condIndepFun_comp_fst_snd_relativeFactorCoupling (hq : Measurable q) (hr : Measurable r)
    (hqr : ν.map r = μ.map q) {Y : Type*} [MeasurableSpace Y] {g : Ω → Y} (hg : Measurable g) :
    CondIndepFun (MeasurableSpace.comap (q ∘ Prod.fst) inferInstance)
      (hq.comp measurable_fst).comap_le (g ∘ Prod.fst) Prod.snd
      (relativeFactorCoupling μ ν q r) :=
  (condIndepFun_fst_snd_relativeFactorCoupling hq hr hqr).comp hg measurable_id

end ProbabilityTheory
