/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Graphon.RelationalStructure
import Mathlib.MeasureTheory.Constructions.Polish.Basic

/-!
# The infinite relational-structure space (AHK umbrella #103, R1b)

The topological / measurable layer of the generic AHK carrier (issue #104). Because
`RelStructure S V = RelCoord S V → Bool` **is** the Boolean product over the coordinate
type, it inherits the product topology and the product σ-algebra directly. The product is
**compact** with no countability assumption; under `[Countable S.Rel]` (and countable value
carriers) the coordinate type is countable, so the space is additionally **Polish** and
**standard Borel**. Over the product σ-algebra — again with no countability needed — its
measurable structure is generated by the coordinate evaluations, hence by the
finite-restriction cylinders; under those countability assumptions the product σ-algebra
agrees with the Borel σ-algebra of the topology.

* `RelSignature.instPolishSpace` — the space is Polish under countability; compactness is
  inherited from the product with no countability assumption;
* `RelSignature.measurable_restrictFin` / `measurable_restrictLE` — the finite restrictions
  are measurable;
* `RelSignature.cylinders` — the finite-restriction cylinders, a π-system
  (`isPiSystem_cylinders`) generating the product σ-algebra (`generateFrom_cylinders_eq`);
* `RelSignature.RelStructure.ext_of_map_restrictFin` — **finite-restriction measure
  extensionality**: two finite measures on the infinite structure space agree once all their
  finite-restriction pushforwards agree.
* `RelSignature.continuous_comap` and its corollaries `continuous_restrict` /
  `continuous_relabel` / `continuous_restrictFin` / `continuous_restrictLE`, plus
  `continuous_pad` / `measurable_pad` — continuity (and measurability) of the sortwise
  actions, needed for the R2 compactness-extension route.

No projective extension here — that is R2.
-/

open MeasureTheory

namespace RelSignature

variable {S : RelSignature}

/-! ### Polish / standard-Borel structure -/

/-- The infinite structure space is Polish (a countable Boolean product). Compact,
metrizable, second-countable, Borel, and standard-Borel are inherited from the product. -/
instance instPolishSpace [Countable S.Rel] {V : S.Srt → Type*} [∀ s, Countable (V s)] :
    PolishSpace (RelStructure S V) := by
  haveI : TopologicalSpace.IsCompletelyMetrizableSpace (RelCoord S V → Bool) := inferInstance
  infer_instance

-- Compactness needs no countability (an arbitrary Boolean product is compact); only the
-- Polish / second-countable / standard-Borel instances require countable coordinates.
example : CompactSpace (RelStructure S (Vinfinite S)) := inferInstance
example [Countable S.Rel] : StandardBorelSpace (RelStructure S (Vinfinite S)) := inferInstance

/-! ### Measurability of the restrictions (over the product σ-algebra) -/

/-- Coordinate evaluation is measurable. -/
theorem measurable_eval {V : S.Srt → Type*} (c : RelCoord S V) :
    Measurable fun σ : RelStructure S V => σ c :=
  measurable_pi_apply c

/-- **Finite restriction is measurable**: each of its coordinates is a coordinate evaluation
of the original structure. -/
theorem measurable_restrictFin (n : S.Srt → ℕ) :
    Measurable (RelStructure.restrictFin n : RelStructure S (Vinfinite S) →
      RelStructure S (Vfinite n)) := by
  rw [measurable_pi_iff]
  intro c
  exact measurable_eval _

/-- **Restriction between size vectors is measurable**. -/
theorem measurable_restrictLE {n m : S.Srt → ℕ} (h : ∀ s, n s ≤ m s) :
    Measurable (RelStructure.restrictLE h : RelStructure S (Vfinite m) →
      RelStructure S (Vfinite n)) := by
  rw [measurable_pi_iff]
  intro c
  exact measurable_eval _

/-! ### The finite-restriction cylinders -/

/-- **The finite-restriction cylinders**: preimages of measurable finite-level events. -/
def cylinders (S : RelSignature) : Set (Set (RelStructure S (Vinfinite S))) :=
  ⋃ n : S.Srt → ℕ,
    {C | ∃ T : Set (RelStructure S (Vfinite n)), MeasurableSet T ∧
      RelStructure.restrictFin n ⁻¹' T = C}

/-- A lower-level cylinder is a higher-level cylinder. -/
theorem restrictFin_preimage_restrictLE {n m : S.Srt → ℕ} (h : ∀ s, n s ≤ m s)
    (T : Set (RelStructure S (Vfinite n))) :
    RelStructure.restrictFin n ⁻¹' T =
      RelStructure.restrictFin m ⁻¹' (RelStructure.restrictLE h ⁻¹' T) := by
  ext σ
  simp only [Set.mem_preimage]
  rw [← RelStructure.restrictLE_restrictFin h σ]

/-- The cylinders form a π-system (align two size vectors at their pointwise maximum). -/
theorem isPiSystem_cylinders : IsPiSystem (cylinders S) := by
  rintro s hs t ht -
  simp only [cylinders, Set.mem_iUnion, Set.mem_setOf_eq] at hs ht ⊢
  obtain ⟨n, S₀, hS₀, rfl⟩ := hs
  obtain ⟨m, T₀, hT₀, rfl⟩ := ht
  refine ⟨fun s => max (n s) (m s),
    RelStructure.restrictLE (fun s => le_max_left _ _) ⁻¹' S₀ ∩
      RelStructure.restrictLE (fun s => le_max_right _ _) ⁻¹' T₀,
    ((measurable_restrictLE _) hS₀).inter ((measurable_restrictLE _) hT₀), ?_⟩
  rw [Set.preimage_inter, ← restrictFin_preimage_restrictLE, ← restrictFin_preimage_restrictLE]

/-- Every coordinate evaluation factors through a finite restriction. -/
theorem exists_restrictFin_eval (c : RelCoord S (Vinfinite S)) :
    ∃ (n : S.Srt → ℕ) (c' : RelCoord S (Vfinite n)),
      ∀ σ : RelStructure S (Vinfinite S), σ c = RelStructure.restrictFin n σ c' := by
  obtain ⟨R, w⟩ := c
  exact ⟨fun _ => (Finset.univ.sup w) + 1,
    ⟨R, fun i => ⟨w i, Nat.lt_succ_of_le (Finset.le_sup (Finset.mem_univ i))⟩⟩, fun _ => rfl⟩

/-- The restriction maps are measurable for the cylinder σ-algebra (by construction). -/
private theorem measurable_restrictFin_generateFrom (n : S.Srt → ℕ) :
    @Measurable (RelStructure S (Vinfinite S)) (RelStructure S (Vfinite n))
      (MeasurableSpace.generateFrom (cylinders S)) _ (RelStructure.restrictFin n) := fun T hT =>
  MeasurableSpace.measurableSet_generateFrom
    (Set.mem_iUnion.mpr ⟨n, T, hT, rfl⟩)

/-- **The cylinders generate the product measurable space** of the infinite structure space
— the coordinate evaluations each factor through a finite restriction. (Under the
countability assumptions yielding the Polish instance, this product σ-algebra agrees with the
Borel σ-algebra of the product topology; the statement itself needs no countability.) -/
theorem generateFrom_cylinders_eq :
    MeasurableSpace.generateFrom (cylinders S) =
      (inferInstance : MeasurableSpace (RelStructure S (Vinfinite S))) := by
  refine le_antisymm (MeasurableSpace.generateFrom_le ?_) ?_
  · rintro s hs
    simp only [cylinders, Set.mem_iUnion, Set.mem_setOf_eq] at hs
    obtain ⟨n, T, hT, rfl⟩ := hs
    exact measurable_restrictFin n hT
  · show MeasurableSpace.pi ≤ MeasurableSpace.generateFrom (cylinders S)
    refine iSup_le fun c => measurable_iff_comap_le.mp ?_
    obtain ⟨n, c', hc⟩ := exists_restrictFin_eval c
    have he : (fun σ : RelStructure S (Vinfinite S) => σ c) =
        (fun τ : RelStructure S (Vfinite n) => τ c') ∘ RelStructure.restrictFin n :=
      funext hc
    rw [he]
    exact (measurable_eval c').comp (measurable_restrictFin_generateFrom n)

/-- **Finite-restriction measure extensionality**: two finite measures on the infinite
structure space with equal pushforwards under every finite restriction are equal. -/
theorem RelStructure.ext_of_map_restrictFin {μ ν : Measure (RelStructure S (Vinfinite S))}
    [IsFiniteMeasure μ] (h : ∀ n, μ.map (RelStructure.restrictFin n) =
      ν.map (RelStructure.restrictFin n)) : μ = ν := by
  refine MeasureTheory.ext_of_generate_finite (cylinders S) generateFrom_cylinders_eq.symm
    isPiSystem_cylinders ?_ ?_
  · rintro s hs
    simp only [cylinders, Set.mem_iUnion, Set.mem_setOf_eq] at hs
    obtain ⟨n, T, hT, rfl⟩ := hs
    rw [← Measure.map_apply (measurable_restrictFin n) hT,
      ← Measure.map_apply (measurable_restrictFin n) hT, h n]
  · have h0 := congrArg (fun m : Measure (RelStructure S (Vfinite fun _ => 0)) => m Set.univ)
      (h (fun _ => 0))
    simpa [Measure.map_apply (measurable_restrictFin (fun _ => 0)) MeasurableSet.univ] using h0

/-! ### Continuity of the sortwise actions

Needed by R2's compactness-extension route: identifying the finite marginals of a weak limit
uses continuity of the restriction maps, not just measurability. -/

/-- **The sortwise pullback is continuous**: `comap f σ = σ ∘ RelCoord.map f` is a
precomposition, hence continuous coordinatewise. This is the reusable primitive. -/
theorem continuous_comap {V W : S.Srt → Type*} (f : ∀ s, V s → W s) :
    Continuous (RelStructure.comap f) := by
  apply continuous_pi
  intro c
  exact continuous_apply (RelCoord.map f c)

/-- Restriction to a sub-carrier is continuous. -/
theorem continuous_restrict {V W : S.Srt → Type*} (e : ∀ s, V s ↪ W s) :
    Continuous (RelStructure.restrict e) := continuous_comap _

/-- Relabelling is continuous. -/
theorem continuous_relabel {V : S.Srt → Type*} (σ : ∀ s, Equiv.Perm (V s)) :
    Continuous (RelStructure.relabel σ) := continuous_comap _

/-- Finite restriction is continuous. -/
theorem continuous_restrictFin (n : S.Srt → ℕ) :
    Continuous (RelStructure.restrictFin (S := S) n) := continuous_comap _

/-- Restriction between size vectors is continuous. -/
theorem continuous_restrictLE {n m : S.Srt → ℕ} (h : ∀ s, n s ≤ m s) :
    Continuous (RelStructure.restrictLE h) := continuous_comap _

open scoped Classical in
/-- **Padding is continuous**: for each coordinate the padded value is, on a fixed
membership condition, either a coordinate evaluation or the constant `false`. -/
theorem continuous_pad {V W : S.Srt → Type*} (e : ∀ s, V s ↪ W s) :
    Continuous (RelStructure.pad e) := by
  apply continuous_pi
  intro d
  by_cases h : ∀ i, d.2 i ∈ Set.range (e (S.argSort d.1 i))
  · simp only [RelStructure.pad, dif_pos h]; exact continuous_apply _
  · simp only [RelStructure.pad, dif_neg h]; exact continuous_const

open scoped Classical in
/-- **Padding is measurable** (over the product σ-algebra; no countability needed) — the
measurable counterpart of `continuous_pad`. -/
theorem measurable_pad {V W : S.Srt → Type*} (e : ∀ s, V s ↪ W s) :
    Measurable (RelStructure.pad e) := by
  apply measurable_pi_iff.mpr
  intro d
  by_cases h : ∀ i, d.2 i ∈ Set.range (e (S.argSort d.1 i))
  · simp only [RelStructure.pad, dif_pos h]; exact measurable_pi_apply _
  · simp only [RelStructure.pad, dif_neg h]; exact measurable_const

end RelSignature
