/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Graphon.RelInvariantAction

/-!
# The raw fixing σ-algebras of finite tagged vertex sets (R4 converse piece 2a, #107)

The **law-independent** factor-algebra layer of the converse representation theorem: for a
finite set `A` of tagged vertices, the σ-algebra of events invariant under every finitely
supported sortwise permutation **fixing every tagged vertex of `A`** — the `A`-relativized
`RelStructure.invariantAlgebra`. Crucially this is *not* "generated by the relation
coordinates inside `A`" (that loses hidden vertex information — a vertex latent carries more
than the relations observed at the vertex); the invariance definition captures everything
the ambient randomness outside `A` cannot move.

Everything here is raw and measure-free — **no completions, no conditional expectations, no
law**. The conditional-independence theorem built on this layer lives in
`Graphon.RelFixingCondIndep`, with `[Countable S.Rel]` supplying
`StandardBorelSpace (RelStructure S (Vinfinite S))`:
`CondIndep (fixingAlgebra (A ∩ B)) (fixingAlgebra A) (fixingAlgebra B)
(fixingAlgebra_le _) M.law` for **every** exchangeable `M` — dissociation is not required.
Sanity specializations: at `A = B`, and likewise at `A = ∅` or `B = ∅`, one outer algebra
*equals* the conditioning algebra `fixingAlgebra (A ∩ B)`, so the statement is tautological —
conditional independence of an algebra from anything given itself; the content is at disjoint
nonempty `A, B`. The standard-Borel factor realizations (stated *modulo the law*) remain a
deliberately separate, later PR.

* `RelSignature.SortwiseFixing` — the `A`-fixing stabilizer (finitely supported + fixes
  `A` pointwise), closed under `1`, `*`, `⁻¹`, and conjugation (`SortwiseFixing.conj`);
* `RelStructure.fixingAlgebra` — the raw fixing σ-algebra, with `fixingAlgebra_le`;
* `RelStructure.fixingAlgebra_mono` — monotone: `A ⊆ B → fixingAlgebra A ≤ fixingAlgebra B`
  (a larger fixed set is a smaller stabilizer, hence more invariant events);
* `RelStructure.fixingAlgebra_empty` — `fixingAlgebra ∅ = invariantAlgebra`
  (near-definitional: the same finitary action);
* `RelStructure.fixingAlgebra_comap_relabel` — **transport**: pulling back along a finitely
  supported relabeling is an *equality of measurable spaces*
  `comap (relabel σ) (fixingAlgebra A) = fixingAlgebra (image σ A)`, by conjugating
  stabilizers;
* `RelSignature.SortwiseFiniteActive` — sortwise families that are the identity outside a
  finite set of sorts, with `SortwiseFixing.conj_of_finiteActive` and
  `RelStructure.fixingAlgebra_comap_relabel_of_finiteActive`: conjugation and transport need
  no vertex-support bound on such a family, since only the active sorts need a common bound.
  This is the support notion the polling permutations have, and it replaces the artificial
  `[Fintype S.Srt]` (whose statements are now the `T = univ` corollaries);
* `RelSignature.FiniteActiveFinSuppPerm` / `RelStructure.finiteActiveFixingAlgebra` — the
  route-local **finite-active subgroup** (finitely supported with finitely many active sorts;
  **countable** under `[Countable S.Srt]`) and the σ-algebra of events invariant under its
  `A`-stabilizer. It contains `fixingAlgebra A`, equals it under `[Fintype S.Srt]`, and
  transports along finite-active relabelings. Countability is what lets an almost-surely
  invariant event be strictified by its invariant hull; the raw fixing algebra keeps its
  contract-level role.
-/

open Function

namespace RelSignature

variable {S : RelSignature}

/-! ### The fixing stabilizer -/

/-- **The `A`-fixing stabilizer**: a sortwise permutation family with common finite support
fixing every tagged vertex of `A`. At `A = ∅` this is `SortwiseFinSupp` — the acting group
of `RelStructure.invariantAlgebra`. -/
def SortwiseFixing (A : Finset (Σ s : S.Srt, Vinfinite S s)) (σ : ∀ _ : S.Srt, Equiv.Perm ℕ) :
    Prop :=
  SortwiseFinSupp (S := S) σ ∧ ∀ v ∈ A, σ v.1 v.2 = v.2

/-- **Finitely many active sorts**: a sortwise permutation family that is the identity on every
sort outside some finite set. This is the support notion the polling permutations actually have —
they move vertices only on the sorts occurring in the poll block — and it is what conjugation and
transport of the fixing algebras need, in place of the artificial `[Fintype S.Srt]`. -/
def SortwiseFiniteActive (σ : ∀ _ : S.Srt, Equiv.Perm ℕ) : Prop :=
  ∃ T : Finset S.Srt, ∀ s, s ∉ T → σ s = 1

theorem SortwiseFiniteActive.inv {σ : ∀ _ : S.Srt, Equiv.Perm ℕ} (hσ : SortwiseFiniteActive σ) :
    SortwiseFiniteActive fun s => (σ s)⁻¹ := by
  obtain ⟨T, hT⟩ := hσ
  exact ⟨T, fun s hs => by show (σ s)⁻¹ = 1; rw [hT s hs, inv_one]⟩

/-- Under finitely many sorts every sortwise family has finitely many active sorts. -/
theorem SortwiseFiniteActive.of_fintype [Fintype S.Srt] (σ : ∀ _ : S.Srt, Equiv.Perm ℕ) :
    SortwiseFiniteActive σ :=
  ⟨Finset.univ, fun s hs => absurd (Finset.mem_univ s) hs⟩

namespace SortwiseFixing

variable {A : Finset (Σ s : S.Srt, Vinfinite S s)} {σ τ : ∀ _ : S.Srt, Equiv.Perm ℕ}

theorem one : SortwiseFixing (S := S) A fun _ => 1 :=
  ⟨SortwiseFinSupp.one, fun _ _ => rfl⟩

theorem mul (hσ : SortwiseFixing (S := S) A σ) (hτ : SortwiseFixing (S := S) A τ) :
    SortwiseFixing (S := S) A fun s => σ s * τ s :=
  ⟨hσ.1.mul hτ.1, fun v hv => by
    show σ v.1 (τ v.1 v.2) = v.2
    rw [hτ.2 v hv, hσ.2 v hv]⟩

theorem inv (hσ : SortwiseFixing (S := S) A σ) :
    SortwiseFixing (S := S) A fun s => (σ s)⁻¹ :=
  ⟨hσ.1.inv, fun v hv => by
    conv_lhs => rw [← hσ.2 v hv]
    exact (σ v.1).symm_apply_apply v.2⟩

open scoped Classical in
/-- **Conjugation moves the fixed set**: conjugating a stabilizer of the image vertex set by
`σ` gives a stabilizer of `A` — the group-theoretic heart of the transport theorem. Finite
support survives because a common bound for `σ` and `τ` bounds the conjugate. -/
theorem conj (hσ : SortwiseFinSupp (S := S) σ)
    (hτ : SortwiseFixing (S := S) (A.image (Sigma.map id fun s => ⇑(σ s))) τ) :
    SortwiseFixing (S := S) A fun s => (σ s)⁻¹ * τ s * σ s := by
  constructor
  · obtain ⟨N, hN⟩ := hσ
    obtain ⟨M, hM⟩ := hτ.1
    refine ⟨max N M, fun s x hx => ?_⟩
    have h1 : σ s x = x := hN s x (le_trans (le_max_left _ _) hx)
    show (σ s)⁻¹ (τ s (σ s x)) = x
    rw [h1, hM s x (le_trans (le_max_right _ _) hx)]
    conv_lhs => rw [← h1]
    exact (σ s).symm_apply_apply x
  · rintro ⟨s, x⟩ hv
    have himg := hτ.2 (Sigma.map id (fun s => ⇑(σ s)) ⟨s, x⟩) (Finset.mem_image_of_mem _ hv)
    show (σ s)⁻¹ (τ s (σ s x)) = x
    rw [show τ s (σ s x) = σ s x from himg]
    exact (σ s).symm_apply_apply x

open scoped Classical in
/-- **Conjugation needs no support bound on `σ` when only finitely many sorts are active**: on
the active sorts the finitely many inverse images below the bound of `τ` give a common bound,
and on every other sort `σ` is the identity, so the conjugate is `τ` there. This is the
hypothesis dropped from `SortwiseFixing.conj`, which is genuinely necessary over infinitely
many active sorts. -/
theorem conj_of_finiteActive (hσ : SortwiseFiniteActive (S := S) σ)
    (hτ : SortwiseFixing (S := S) (A.image (Sigma.map id fun s => ⇑(σ s))) τ) :
    SortwiseFixing (S := S) A fun s => (σ s)⁻¹ * τ s * σ s := by
  obtain ⟨T, hT⟩ := hσ
  constructor
  · obtain ⟨M, hM⟩ := hτ.1
    refine ⟨max M ((T.sup fun s : S.Srt => (Finset.range M).sup fun y => (σ s)⁻¹ y) + 1),
      fun s x hx => ?_⟩
    show (σ s)⁻¹ (τ s (σ s x)) = x
    by_cases hs : s ∈ T
    · have hbig : M ≤ σ s x := by
        by_contra hlt
        push Not at hlt
        have h1 : x = (σ s)⁻¹ (σ s x) := ((σ s).symm_apply_apply x).symm
        have h2 : (σ s)⁻¹ (σ s x) ≤ (Finset.range M).sup fun y => (σ s)⁻¹ y :=
          Finset.le_sup (f := fun y => (σ s)⁻¹ y) (Finset.mem_range.mpr hlt)
        have h3 : ((Finset.range M).sup fun y => (σ s)⁻¹ y) ≤
            T.sup fun s : S.Srt => (Finset.range M).sup fun y => (σ s)⁻¹ y :=
          Finset.le_sup (f := fun s : S.Srt => (Finset.range M).sup fun y => (σ s)⁻¹ y) hs
        have h4 := le_max_right M
          ((T.sup fun s : S.Srt => (Finset.range M).sup fun y => (σ s)⁻¹ y) + 1)
        omega
      rw [hM s (σ s x) hbig]
      exact (σ s).symm_apply_apply x
    · rw [hT s hs]
      show τ s x = x
      exact hM s x (le_trans (le_max_left _ _) hx)
  · rintro ⟨s, x⟩ hv
    have himg := hτ.2 (Sigma.map id (fun s => ⇑(σ s)) ⟨s, x⟩) (Finset.mem_image_of_mem _ hv)
    show (σ s)⁻¹ (τ s (σ s x)) = x
    rw [show τ s (σ s x) = σ s x from himg]
    exact (σ s).symm_apply_apply x

open scoped Classical in
/-- **Conjugation under finitely many sorts needs no support bound on `σ`**: the finite-active
statement at `T = univ`. -/
theorem conj_of_fintype [Fintype S.Srt]
    (hτ : SortwiseFixing (S := S) (A.image (Sigma.map id fun s => ⇑(σ s))) τ) :
    SortwiseFixing (S := S) A fun s => (σ s)⁻¹ * τ s * σ s :=
  conj_of_finiteActive (SortwiseFiniteActive.of_fintype σ) hτ

end SortwiseFixing

/-! ### The raw fixing σ-algebra -/

/-- **The raw fixing σ-algebra** of a finite tagged vertex set `A`: measurable events
invariant under every finitely supported sortwise relabeling fixing every tagged vertex of
`A`. Law-independent by construction — completions, conditional expectations, and mod-null
factor realizations explicitly carry a law and live in later layers. -/
@[implicit_reducible]
def RelStructure.fixingAlgebra (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    MeasurableSpace (RelStructure S (Vinfinite S)) where
  MeasurableSet' E := MeasurableSet E ∧
    ∀ σ, SortwiseFixing (S := S) A σ → RelStructure.relabel σ ⁻¹' E = E
  measurableSet_empty := ⟨MeasurableSet.empty, fun _ _ => Set.preimage_empty⟩
  measurableSet_compl := fun E hE => ⟨hE.1.compl, fun σ h => by
    rw [Set.preimage_compl, hE.2 σ h]⟩
  measurableSet_iUnion := fun f hf => ⟨MeasurableSet.iUnion fun i => (hf i).1, fun σ h => by
    rw [Set.preimage_iUnion]
    exact Set.iUnion_congr fun i => (hf i).2 σ h⟩

theorem RelStructure.fixingAlgebra_le (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    RelStructure.fixingAlgebra (S := S) A ≤
      (inferInstance : MeasurableSpace (RelStructure S (Vinfinite S))) :=
  fun _ hE => hE.1

/-- **Monotonicity**: a larger fixed set is a smaller stabilizer, hence more invariant
events. -/
theorem RelStructure.fixingAlgebra_mono {A B : Finset (Σ s : S.Srt, Vinfinite S s)} (hAB : A ⊆ B) :
    RelStructure.fixingAlgebra (S := S) A ≤ RelStructure.fixingAlgebra (S := S) B :=
  fun _ hE => ⟨hE.1, fun σ hσ => hE.2 σ ⟨hσ.1, fun v hv => hσ.2 v (hAB hv)⟩⟩

/-- **The bottom factor is the invariant σ-algebra** — near-definitional: at `A = ∅` the
fixing condition is vacuous and the stabilizer is the full finitely supported group, so
dissociation/ergodicity (R3, #106) trivializes exactly this factor. -/
theorem RelStructure.fixingAlgebra_empty :
    RelStructure.fixingAlgebra (S := S) ∅ = RelStructure.invariantAlgebra := by
  refine MeasurableSpace.ext fun E => ⟨fun hE => ⟨hE.1, fun σ hσ => hE.2 σ ⟨hσ, fun v hv =>
    absurd hv (Finset.notMem_empty v)⟩⟩, fun hE => ⟨hE.1, fun σ hσ => hE.2 σ hσ.1⟩⟩

/-! ### Transport -/

/-- Relabelings compose contravariantly (permutation product acts inner-first). -/
theorem RelStructure.relabel_comp_relabel (σ τ : ∀ _ : S.Srt, Equiv.Perm ℕ) :
    RelStructure.relabel (V := Vinfinite S) σ ∘ RelStructure.relabel τ =
      RelStructure.relabel fun s => τ s * σ s := by
  funext X
  show RelStructure.comap _ (RelStructure.comap _ X) = _
  rw [← RelStructure.comap_comp]
  rfl

theorem RelStructure.relabel_preimage_relabel_preimage
    (τ σ : ∀ _ : S.Srt, Equiv.Perm ℕ) (E : Set (RelStructure S (Vinfinite S))) :
    RelStructure.relabel τ ⁻¹' (RelStructure.relabel σ ⁻¹' E) =
      RelStructure.relabel (fun s => τ s * σ s) ⁻¹' E := by
  rw [← Set.preimage_comp, RelStructure.relabel_comp_relabel]

open scoped Classical in
/-- One-sided transport, parametric in the conjugation closure: pulling an invariant event
back along a relabeling whose conjugation carries image-stabilizers to `A`-stabilizers lands
in the fixing algebra of the image vertex set. -/
private theorem fixingAlgebra_comap_relabel_le (σ : ∀ _ : S.Srt, Equiv.Perm ℕ)
    (A : Finset (Σ s : S.Srt, Vinfinite S s))
    (hconj : ∀ τ, SortwiseFixing (S := S) (A.image (Sigma.map id fun s => ⇑(σ s))) τ →
      SortwiseFixing (S := S) A fun s => (σ s)⁻¹ * τ s * σ s) :
    MeasurableSpace.comap (RelStructure.relabel σ) (RelStructure.fixingAlgebra (S := S) A) ≤
      RelStructure.fixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))) := by
  rintro - ⟨E, hE, rfl⟩
  refine ⟨measurable_relabel σ hE.1, fun τ hτ => ?_⟩
  rw [RelStructure.relabel_preimage_relabel_preimage,
    show (fun s => τ s * σ s) = fun s => σ s * ((σ s)⁻¹ * τ s * σ s) from
      funext fun s => by group,
    ← RelStructure.relabel_preimage_relabel_preimage, hE.2 _ (hconj τ hτ)]

open scoped Classical in
/-- Two one-sided transports (for `σ` and for its inverse) assemble into the transport
equality: the inverse inclusion is pushed through `comap` composition and the collapse of
`σ⁻¹ ∘ σ` on images. -/
private theorem fixingAlgebra_comap_relabel_of_le (σ : ∀ _ : S.Srt, Equiv.Perm ℕ)
    (A : Finset (Σ s : S.Srt, Vinfinite S s))
    (h₁ : MeasurableSpace.comap (RelStructure.relabel σ)
        (RelStructure.fixingAlgebra (S := S) A) ≤
      RelStructure.fixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))))
    (h₂ : MeasurableSpace.comap (RelStructure.relabel fun s => (σ s)⁻¹)
        (RelStructure.fixingAlgebra (S := S) (A.image (Sigma.map id fun s => ⇑(σ s)))) ≤
      RelStructure.fixingAlgebra ((A.image (Sigma.map id fun s => ⇑(σ s))).image
        (Sigma.map id fun s => ⇑(σ s)⁻¹))) :
    MeasurableSpace.comap (RelStructure.relabel σ) (RelStructure.fixingAlgebra (S := S) A) =
      RelStructure.fixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))) := by
  refine le_antisymm h₁ ?_
  have himg : ((A.image (Sigma.map id fun s => ⇑(σ s))).image
      (Sigma.map id fun s => ⇑(σ s)⁻¹)) = A := by
    rw [Finset.image_image]
    refine (Finset.image_congr fun v _ => ?_).trans A.image_id
    obtain ⟨s, x⟩ := v
    show ⟨s, (σ s)⁻¹ (σ s x)⟩ = (⟨s, x⟩ : Σ s : S.Srt, Vinfinite S s)
    rw [show (σ s)⁻¹ (σ s x) = x from (σ s).symm_apply_apply x]
  rw [himg] at h₂
  have := MeasurableSpace.comap_mono (g := RelStructure.relabel (V := Vinfinite S) σ) h₂
  rwa [MeasurableSpace.comap_comp, RelStructure.relabel_comp_relabel,
    show (fun s => σ s * (σ s)⁻¹) = fun _ : S.Srt => (1 : Equiv.Perm ℕ) from
      funext fun s => mul_inv_cancel (σ s),
    show RelStructure.relabel (V := Vinfinite S) (fun _ : S.Srt => (1 : Equiv.Perm ℕ)) = id from
      rfl,
    MeasurableSpace.comap_id] at this

open scoped Classical in
/-- **Transport of the fixing σ-algebra** along a finitely supported sortwise relabeling —
an equality of pulled-back measurable spaces, not merely an event-membership equivalence:
the pullback of the `A`-fixing algebra is the fixing algebra of the image vertex set.
Stabilizers conjugate (`SortwiseFixing.conj`); the reverse inclusion is the forward one for
`σ⁻¹` transported through `comap` composition. Over infinitely many sorts the finite-support
hypothesis is genuinely necessary; under `[Fintype S.Srt]` see
`fixingAlgebra_comap_relabel_of_fintype`. -/
theorem RelStructure.fixingAlgebra_comap_relabel {σ : ∀ _ : S.Srt, Equiv.Perm ℕ}
    (hσ : SortwiseFinSupp (S := S) σ) (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    MeasurableSpace.comap (RelStructure.relabel σ) (RelStructure.fixingAlgebra (S := S) A) =
      RelStructure.fixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))) :=
  fixingAlgebra_comap_relabel_of_le σ A
    (fixingAlgebra_comap_relabel_le σ A fun _ hτ => SortwiseFixing.conj hσ hτ)
    (fixingAlgebra_comap_relabel_le _ _ fun _ hτ => SortwiseFixing.conj hσ.inv hτ)

open scoped Classical in
/-- **Transport along a sortwise permutation with finitely many active sorts**: no support bound
on `σ` is needed, since conjugation recovers a common bound on the active sorts
(`SortwiseFixing.conj_of_finiteActive`). -/
theorem RelStructure.fixingAlgebra_comap_relabel_of_finiteActive
    {σ : ∀ _ : S.Srt, Equiv.Perm ℕ} (hσ : SortwiseFiniteActive (S := S) σ)
    (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    MeasurableSpace.comap (RelStructure.relabel σ) (RelStructure.fixingAlgebra (S := S) A) =
      RelStructure.fixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))) :=
  fixingAlgebra_comap_relabel_of_le σ A
    (fixingAlgebra_comap_relabel_le σ A fun _ hτ => SortwiseFixing.conj_of_finiteActive hσ hτ)
    (fixingAlgebra_comap_relabel_le _ _ fun _ hτ =>
      SortwiseFixing.conj_of_finiteActive hσ.inv hτ)

open scoped Classical in
/-- **Transport under finitely many sorts holds for an arbitrary sortwise permutation
family**: the finite-active statement at `T = univ`. -/
theorem RelStructure.fixingAlgebra_comap_relabel_of_fintype [Fintype S.Srt]
    (σ : ∀ _ : S.Srt, Equiv.Perm ℕ) (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    MeasurableSpace.comap (RelStructure.relabel σ) (RelStructure.fixingAlgebra (S := S) A) =
      RelStructure.fixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))) :=
  RelStructure.fixingAlgebra_comap_relabel_of_finiteActive (SortwiseFiniteActive.of_fintype σ) A

/-! ### The finite-active subgroup and its fixing σ-algebra

Route-local auxiliaries for the R4 converse. The contract-level `fixingAlgebra` demands invariance
under *every* finitely supported sortwise permutation; over infinitely many sorts that group is
uncountable (a permutation of `{0, …, N-1}` may be chosen independently on each sort), so the
countable invariant-hull argument, which strictifies an almost-surely invariant event by
intersecting its translates, is unavailable for the full group. The finitely supported
permutations with **finitely many active sorts** form a countable subgroup under
`[Countable S.Srt]`, and invariance under it defines a larger σ-algebra in which the countable
invariant hull strictifies almost-sure invariance. Under `[Fintype S.Srt]` the two notions
coincide. -/

/-- Finite support together with finitely many active sorts is closed under composition. -/
theorem SortwiseFiniteActive.mul {σ τ : ∀ _ : S.Srt, Equiv.Perm ℕ}
    (hσ : SortwiseFiniteActive (S := S) σ) (hτ : SortwiseFiniteActive (S := S) τ) :
    SortwiseFiniteActive (S := S) fun s => σ s * τ s := by
  classical
  obtain ⟨T, hT⟩ := hσ
  obtain ⟨U, hU⟩ := hτ
  refine ⟨T ∪ U, fun s hs => ?_⟩
  show σ s * τ s = 1
  rw [hT s fun h => hs (Finset.mem_union_left _ h), hU s fun h => hs (Finset.mem_union_right _ h),
    one_mul]

theorem SortwiseFiniteActive.one : SortwiseFiniteActive (S := S) fun _ => 1 :=
  ⟨∅, fun _ _ => rfl⟩

/-- **The finite-active finitely supported permutations**, as a subgroup. -/
def finiteActiveFinSuppSubgroup (S : RelSignature) : Subgroup (∀ _ : S.Srt, Equiv.Perm ℕ) where
  carrier := {σ | SortwiseFinSupp (S := S) σ ∧ SortwiseFiniteActive (S := S) σ}
  mul_mem' := fun hσ hτ => ⟨SortwiseFinSupp.mul hσ.1 hτ.1, SortwiseFiniteActive.mul hσ.2 hτ.2⟩
  one_mem' := ⟨SortwiseFinSupp.one, SortwiseFiniteActive.one⟩
  inv_mem' := fun hσ => ⟨SortwiseFinSupp.inv hσ.1, SortwiseFiniteActive.inv hσ.2⟩

/-- A finitely supported sortwise permutation family with finitely many active sorts, bundled. -/
abbrev FiniteActiveFinSuppPerm (S : RelSignature) := finiteActiveFinSuppSubgroup S

@[simp] theorem mem_finiteActiveFinSuppSubgroup {σ : ∀ _ : S.Srt, Equiv.Perm ℕ} :
    σ ∈ finiteActiveFinSuppSubgroup S ↔
      SortwiseFinSupp (S := S) σ ∧ SortwiseFiniteActive (S := S) σ := Iff.rfl

/-- Under finitely many sorts every finitely supported family is finite-active. -/
theorem finiteActiveFinSuppSubgroup_eq_of_fintype [Fintype S.Srt] :
    finiteActiveFinSuppSubgroup S = sortwiseFinSuppSubgroup S :=
  Subgroup.ext fun σ => ⟨fun h => h.1, fun h => ⟨h, SortwiseFiniteActive.of_fintype σ⟩⟩

/-- **The finite-active subgroup is countable** under `[Countable S.Srt]`: a member is determined
by its finite graph on the active sorts below its support bound. -/
instance [Countable S.Srt] : Countable (FiniteActiveFinSuppPerm S) := by
  classical
  let enc : FiniteActiveFinSuppPerm S → Finset (S.Srt × ℕ × ℕ) := fun σ =>
    ((Classical.choose σ.2.2) ×ˢ Finset.range (Classical.choose σ.2.1)).image
      fun p => (p.1, p.2, σ.1 p.1 p.2)
  refine Function.Injective.countable (f := enc) fun σ τ h' => ?_
  -- membership in the graph is determined by the value
  have hval : ∀ (ρ : FiniteActiveFinSuppPerm S) (s : S.Srt) (x y : ℕ),
      (s, x, y) ∈ enc ρ ↔ (s ∈ Classical.choose ρ.2.2 ∧ x < Classical.choose ρ.2.1) ∧
        ρ.1 s x = y := by
    intro ρ s x y
    simp only [enc, Finset.mem_image, Finset.mem_product, Finset.mem_range, Prod.exists]
    constructor
    · rintro ⟨s', x', ⟨hs', hx'⟩, hxy⟩
      obtain ⟨rfl, hxy'⟩ := Prod.mk.inj hxy
      obtain ⟨rfl, rfl⟩ := Prod.mk.inj hxy'
      exact ⟨⟨hs', hx'⟩, rfl⟩
    · rintro ⟨⟨hs, hx⟩, rfl⟩
      exact ⟨s, x, ⟨hs, hx⟩, rfl⟩
  -- outside the graph a member is the identity
  have hout : ∀ (ρ : FiniteActiveFinSuppPerm S) (s : S.Srt) (x : ℕ),
      ¬ (s ∈ Classical.choose ρ.2.2 ∧ x < Classical.choose ρ.2.1) → ρ.1 s x = x := by
    intro ρ s x hn
    by_cases hs : s ∈ Classical.choose ρ.2.2
    · have hx : Classical.choose ρ.2.1 ≤ x := Nat.le_of_not_lt fun h => hn ⟨hs, h⟩
      exact Classical.choose_spec ρ.2.1 s x hx
    · rw [Classical.choose_spec ρ.2.2 s hs]
      rfl
  apply Subtype.ext
  funext s
  apply Equiv.ext
  intro x
  by_cases hσ : s ∈ Classical.choose σ.2.2 ∧ x < Classical.choose σ.2.1
  · have hmem : (s, x, σ.1 s x) ∈ enc τ := by
      rw [← h']
      exact (hval σ s x _).mpr ⟨hσ, rfl⟩
    exact ((hval τ s x _).mp hmem).2.symm
  · by_cases hτ : s ∈ Classical.choose τ.2.2 ∧ x < Classical.choose τ.2.1
    · have hmem : (s, x, τ.1 s x) ∈ enc σ := by
        rw [h']
        exact (hval τ s x _).mpr ⟨hτ, rfl⟩
      exact ((hval σ s x _).mp hmem).2
    · rw [hout σ s x hσ, hout τ s x hτ]

/-- **The finite-active fixing σ-algebra** of `A`: measurable events invariant under every
finite-active finitely supported sortwise relabeling fixing `A` pointwise. Contains the
contract-level `fixingAlgebra A`, with equality under `[Fintype S.Srt]`. -/
@[implicit_reducible]
def RelStructure.finiteActiveFixingAlgebra (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    MeasurableSpace (RelStructure S (Vinfinite S)) where
  MeasurableSet' E := MeasurableSet E ∧
    ∀ σ, SortwiseFixing (S := S) A σ → SortwiseFiniteActive (S := S) σ →
      RelStructure.relabel σ ⁻¹' E = E
  measurableSet_empty := ⟨MeasurableSet.empty, fun _ _ _ => Set.preimage_empty⟩
  measurableSet_compl := fun E hE => ⟨hE.1.compl, fun σ h h' => by
    rw [Set.preimage_compl, hE.2 σ h h']⟩
  measurableSet_iUnion := fun f hf => ⟨MeasurableSet.iUnion fun i => (hf i).1, fun σ h h' => by
    rw [Set.preimage_iUnion]
    exact Set.iUnion_congr fun i => (hf i).2 σ h h'⟩

theorem RelStructure.finiteActiveFixingAlgebra_le (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    RelStructure.finiteActiveFixingAlgebra (S := S) A ≤
      (inferInstance : MeasurableSpace (RelStructure S (Vinfinite S))) :=
  fun _ hE => hE.1

/-- **Raw containment**: invariance under all finitely supported relabelings fixing `A` implies
invariance under the finite-active ones. -/
theorem RelStructure.fixingAlgebra_le_finiteActiveFixingAlgebra
    (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    RelStructure.fixingAlgebra (S := S) A ≤ RelStructure.finiteActiveFixingAlgebra A :=
  fun _ hE => ⟨hE.1, fun σ hσ _ => hE.2 σ hσ⟩

/-- Under finitely many sorts the two fixing σ-algebras coincide. -/
theorem RelStructure.finiteActiveFixingAlgebra_eq_of_fintype [Fintype S.Srt]
    (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    RelStructure.finiteActiveFixingAlgebra (S := S) A = RelStructure.fixingAlgebra A :=
  le_antisymm (fun _ hE => ⟨hE.1, fun σ hσ => hE.2 σ hσ (SortwiseFiniteActive.of_fintype σ)⟩)
    (RelStructure.fixingAlgebra_le_finiteActiveFixingAlgebra A)

open scoped Classical in
/-- One-sided transport of the finite-active fixing algebra along a finite-active relabeling:
conjugating a finite-active stabilizer of the image by a finite-active `σ` gives a finite-active
stabilizer of `A`. -/
private theorem finiteActiveFixingAlgebra_comap_relabel_le {σ : ∀ _ : S.Srt, Equiv.Perm ℕ}
    (hσ : SortwiseFiniteActive (S := S) σ) (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    MeasurableSpace.comap (RelStructure.relabel σ)
        (RelStructure.finiteActiveFixingAlgebra (S := S) A) ≤
      RelStructure.finiteActiveFixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))) := by
  rintro - ⟨E, hE, rfl⟩
  refine ⟨measurable_relabel σ hE.1, fun τ hτ hτ' => ?_⟩
  rw [RelStructure.relabel_preimage_relabel_preimage,
    show (fun s => τ s * σ s) = fun s => σ s * ((σ s)⁻¹ * τ s * σ s) from
      funext fun s => by group,
    ← RelStructure.relabel_preimage_relabel_preimage,
    hE.2 _ (SortwiseFixing.conj_of_finiteActive hσ hτ) (by
      have h1 : SortwiseFiniteActive (S := S) fun s => (σ s)⁻¹ * τ s := hσ.inv.mul hτ'
      exact h1.mul hσ)]

open scoped Classical in
/-- **Transport of the finite-active fixing σ-algebra** along a finite-active relabeling — an
equality of pulled-back measurable spaces, the finite-active counterpart of
`fixingAlgebra_comap_relabel`. -/
theorem RelStructure.finiteActiveFixingAlgebra_comap_relabel {σ : ∀ _ : S.Srt, Equiv.Perm ℕ}
    (hσ : SortwiseFiniteActive (S := S) σ) (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    MeasurableSpace.comap (RelStructure.relabel σ)
        (RelStructure.finiteActiveFixingAlgebra (S := S) A) =
      RelStructure.finiteActiveFixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))) := by
  refine le_antisymm (finiteActiveFixingAlgebra_comap_relabel_le hσ A) ?_
  have h₂ := finiteActiveFixingAlgebra_comap_relabel_le hσ.inv
    (A.image (Sigma.map id fun s => ⇑(σ s)))
  have himg : ((A.image (Sigma.map id fun s => ⇑(σ s))).image
      (Sigma.map id fun s => ⇑(σ s)⁻¹)) = A := by
    rw [Finset.image_image]
    refine (Finset.image_congr fun v _ => ?_).trans A.image_id
    obtain ⟨s, x⟩ := v
    show ⟨s, (σ s)⁻¹ (σ s x)⟩ = (⟨s, x⟩ : Σ s : S.Srt, Vinfinite S s)
    rw [show (σ s)⁻¹ (σ s x) = x from (σ s).symm_apply_apply x]
  rw [himg] at h₂
  have := MeasurableSpace.comap_mono (g := RelStructure.relabel (V := Vinfinite S) σ) h₂
  rwa [MeasurableSpace.comap_comp, RelStructure.relabel_comp_relabel,
    show (fun s => σ s * (σ s)⁻¹) = fun _ : S.Srt => (1 : Equiv.Perm ℕ) from
      funext fun s => mul_inv_cancel (σ s),
    show RelStructure.relabel (V := Vinfinite S) (fun _ : S.Srt => (1 : Equiv.Perm ℕ)) = id from
      rfl,
    MeasurableSpace.comap_id] at this

end RelSignature
