/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Graphon.RelInvariantAction

/-!
# The raw fixing σ-algebras of finite tagged vertex sets (R4 converse piece 2a, #107)

The **law-independent** factor-algebra layer of the converse representation theorem: for a
finite set `A` of tagged vertices, the σ-algebra of events invariant under every finitely
supported sortwise permutation **fixing every tagged vertex of `A`** — the `A`-relativized
`RelStructure.invariantAlgebra`. Crucially this is *not* "generated by the relation
coordinates inside `A`" (that loses hidden vertex information — a vertex latent carries more
than the relations observed at the vertex); the invariance definition captures everything
the ambient randomness outside `A` cannot move.

Everything here is raw and measure-free — **no completions, no conditional expectations, no
law**. The conditional-independence theorem built on this layer lives in
`Graphon.RelFixingCondIndep`, with `[Countable S.Rel]` supplying
`StandardBorelSpace (RelStructure S (Vinfinite S))`:
`CondIndep (fixingAlgebra (A ∩ B)) (fixingAlgebra A) (fixingAlgebra B)
(fixingAlgebra_le _) M.law` for **every** exchangeable `M` — dissociation is not required.
Sanity specializations: at `A = B`, and likewise at `A = ∅` or `B = ∅`, one outer algebra
*equals* the conditioning algebra `fixingAlgebra (A ∩ B)`, so the statement is tautological —
conditional independence of an algebra from anything given itself; the content is at disjoint
nonempty `A, B`. The standard-Borel factor realizations (stated *modulo the law*) remain a
deliberately separate, later PR.

* `RelSignature.SortwiseFixing` — the `A`-fixing stabilizer (finitely supported + fixes
  `A` pointwise), closed under `1`, `*`, `⁻¹`, and conjugation (`SortwiseFixing.conj`);
* `RelStructure.fixingAlgebra` — the raw fixing σ-algebra, with `fixingAlgebra_le`;
* `RelStructure.fixingAlgebra_mono` — monotone: `A ⊆ B → fixingAlgebra A ≤ fixingAlgebra B`
  (a larger fixed set is a smaller stabilizer, hence more invariant events);
* `RelStructure.fixingAlgebra_empty` — `fixingAlgebra ∅ = invariantAlgebra`
  (near-definitional: the same finitary action);
* `RelStructure.fixingAlgebra_comap_relabel` — **transport**: pulling back along a finitely
  supported relabeling is an *equality of measurable spaces*
  `comap (relabel σ) (fixingAlgebra A) = fixingAlgebra (image σ A)`, by conjugating
  stabilizers;
* `RelSignature.SortwiseFiniteActive` — sortwise families that are the identity outside a
  finite set of sorts, with `SortwiseFixing.conj_of_finiteActive` and
  `RelStructure.fixingAlgebra_comap_relabel_of_finiteActive`: conjugation and transport need
  no vertex-support bound on such a family, since only the active sorts need a common bound.
  This is the support notion the polling permutations have, and it replaces the artificial
  `[Fintype S.Srt]` (whose statements are now the `T = univ` corollaries).
-/

open Function

namespace RelSignature

variable {S : RelSignature}

/-! ### The fixing stabilizer -/

/-- **The `A`-fixing stabilizer**: a sortwise permutation family with common finite support
fixing every tagged vertex of `A`. At `A = ∅` this is `SortwiseFinSupp` — the acting group
of `RelStructure.invariantAlgebra`. -/
def SortwiseFixing (A : Finset (Σ s : S.Srt, Vinfinite S s)) (σ : ∀ _ : S.Srt, Equiv.Perm ℕ) :
    Prop :=
  SortwiseFinSupp (S := S) σ ∧ ∀ v ∈ A, σ v.1 v.2 = v.2

/-- **Finitely many active sorts**: a sortwise permutation family that is the identity on every
sort outside some finite set. This is the support notion the polling permutations actually have —
they move vertices only on the sorts occurring in the poll block — and it is what conjugation and
transport of the fixing algebras need, in place of the artificial `[Fintype S.Srt]`. -/
def SortwiseFiniteActive (σ : ∀ _ : S.Srt, Equiv.Perm ℕ) : Prop :=
  ∃ T : Finset S.Srt, ∀ s, s ∉ T → σ s = 1

theorem SortwiseFiniteActive.inv {σ : ∀ _ : S.Srt, Equiv.Perm ℕ} (hσ : SortwiseFiniteActive σ) :
    SortwiseFiniteActive fun s => (σ s)⁻¹ := by
  obtain ⟨T, hT⟩ := hσ
  exact ⟨T, fun s hs => by show (σ s)⁻¹ = 1; rw [hT s hs, inv_one]⟩

/-- Under finitely many sorts every sortwise family has finitely many active sorts. -/
theorem SortwiseFiniteActive.of_fintype [Fintype S.Srt] (σ : ∀ _ : S.Srt, Equiv.Perm ℕ) :
    SortwiseFiniteActive σ :=
  ⟨Finset.univ, fun s hs => absurd (Finset.mem_univ s) hs⟩

namespace SortwiseFixing

variable {A : Finset (Σ s : S.Srt, Vinfinite S s)} {σ τ : ∀ _ : S.Srt, Equiv.Perm ℕ}

theorem one : SortwiseFixing (S := S) A fun _ => 1 :=
  ⟨SortwiseFinSupp.one, fun _ _ => rfl⟩

theorem mul (hσ : SortwiseFixing (S := S) A σ) (hτ : SortwiseFixing (S := S) A τ) :
    SortwiseFixing (S := S) A fun s => σ s * τ s :=
  ⟨hσ.1.mul hτ.1, fun v hv => by
    show σ v.1 (τ v.1 v.2) = v.2
    rw [hτ.2 v hv, hσ.2 v hv]⟩

theorem inv (hσ : SortwiseFixing (S := S) A σ) :
    SortwiseFixing (S := S) A fun s => (σ s)⁻¹ :=
  ⟨hσ.1.inv, fun v hv => by
    conv_lhs => rw [← hσ.2 v hv]
    exact (σ v.1).symm_apply_apply v.2⟩

open scoped Classical in
/-- **Conjugation moves the fixed set**: conjugating a stabilizer of the image vertex set by
`σ` gives a stabilizer of `A` — the group-theoretic heart of the transport theorem. Finite
support survives because a common bound for `σ` and `τ` bounds the conjugate. -/
theorem conj (hσ : SortwiseFinSupp (S := S) σ)
    (hτ : SortwiseFixing (S := S) (A.image (Sigma.map id fun s => ⇑(σ s))) τ) :
    SortwiseFixing (S := S) A fun s => (σ s)⁻¹ * τ s * σ s := by
  constructor
  · obtain ⟨N, hN⟩ := hσ
    obtain ⟨M, hM⟩ := hτ.1
    refine ⟨max N M, fun s x hx => ?_⟩
    have h1 : σ s x = x := hN s x (le_trans (le_max_left _ _) hx)
    show (σ s)⁻¹ (τ s (σ s x)) = x
    rw [h1, hM s x (le_trans (le_max_right _ _) hx)]
    conv_lhs => rw [← h1]
    exact (σ s).symm_apply_apply x
  · rintro ⟨s, x⟩ hv
    have himg := hτ.2 (Sigma.map id (fun s => ⇑(σ s)) ⟨s, x⟩) (Finset.mem_image_of_mem _ hv)
    show (σ s)⁻¹ (τ s (σ s x)) = x
    rw [show τ s (σ s x) = σ s x from himg]
    exact (σ s).symm_apply_apply x

open scoped Classical in
/-- **Conjugation needs no support bound on `σ` when only finitely many sorts are active**: on
the active sorts the finitely many inverse images below the bound of `τ` give a common bound,
and on every other sort `σ` is the identity, so the conjugate is `τ` there. This is the
hypothesis dropped from `SortwiseFixing.conj`, which is genuinely necessary over infinitely
many active sorts. -/
theorem conj_of_finiteActive (hσ : SortwiseFiniteActive (S := S) σ)
    (hτ : SortwiseFixing (S := S) (A.image (Sigma.map id fun s => ⇑(σ s))) τ) :
    SortwiseFixing (S := S) A fun s => (σ s)⁻¹ * τ s * σ s := by
  obtain ⟨T, hT⟩ := hσ
  constructor
  · obtain ⟨M, hM⟩ := hτ.1
    refine ⟨max M ((T.sup fun s : S.Srt => (Finset.range M).sup fun y => (σ s)⁻¹ y) + 1),
      fun s x hx => ?_⟩
    show (σ s)⁻¹ (τ s (σ s x)) = x
    by_cases hs : s ∈ T
    · have hbig : M ≤ σ s x := by
        by_contra hlt
        push Not at hlt
        have h1 : x = (σ s)⁻¹ (σ s x) := ((σ s).symm_apply_apply x).symm
        have h2 : (σ s)⁻¹ (σ s x) ≤ (Finset.range M).sup fun y => (σ s)⁻¹ y :=
          Finset.le_sup (f := fun y => (σ s)⁻¹ y) (Finset.mem_range.mpr hlt)
        have h3 : ((Finset.range M).sup fun y => (σ s)⁻¹ y) ≤
            T.sup fun s : S.Srt => (Finset.range M).sup fun y => (σ s)⁻¹ y :=
          Finset.le_sup (f := fun s : S.Srt => (Finset.range M).sup fun y => (σ s)⁻¹ y) hs
        have h4 := le_max_right M
          ((T.sup fun s : S.Srt => (Finset.range M).sup fun y => (σ s)⁻¹ y) + 1)
        omega
      rw [hM s (σ s x) hbig]
      exact (σ s).symm_apply_apply x
    · rw [hT s hs]
      show τ s x = x
      exact hM s x (le_trans (le_max_left _ _) hx)
  · rintro ⟨s, x⟩ hv
    have himg := hτ.2 (Sigma.map id (fun s => ⇑(σ s)) ⟨s, x⟩) (Finset.mem_image_of_mem _ hv)
    show (σ s)⁻¹ (τ s (σ s x)) = x
    rw [show τ s (σ s x) = σ s x from himg]
    exact (σ s).symm_apply_apply x

open scoped Classical in
/-- **Conjugation under finitely many sorts needs no support bound on `σ`**: the finite-active
statement at `T = univ`. -/
theorem conj_of_fintype [Fintype S.Srt]
    (hτ : SortwiseFixing (S := S) (A.image (Sigma.map id fun s => ⇑(σ s))) τ) :
    SortwiseFixing (S := S) A fun s => (σ s)⁻¹ * τ s * σ s :=
  conj_of_finiteActive (SortwiseFiniteActive.of_fintype σ) hτ

end SortwiseFixing

/-! ### The raw fixing σ-algebra -/

/-- **The raw fixing σ-algebra** of a finite tagged vertex set `A`: measurable events
invariant under every finitely supported sortwise relabeling fixing every tagged vertex of
`A`. Law-independent by construction — completions, conditional expectations, and mod-null
factor realizations explicitly carry a law and live in later layers. -/
@[implicit_reducible]
def RelStructure.fixingAlgebra (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    MeasurableSpace (RelStructure S (Vinfinite S)) where
  MeasurableSet' E := MeasurableSet E ∧
    ∀ σ, SortwiseFixing (S := S) A σ → RelStructure.relabel σ ⁻¹' E = E
  measurableSet_empty := ⟨MeasurableSet.empty, fun _ _ => Set.preimage_empty⟩
  measurableSet_compl := fun E hE => ⟨hE.1.compl, fun σ h => by
    rw [Set.preimage_compl, hE.2 σ h]⟩
  measurableSet_iUnion := fun f hf => ⟨MeasurableSet.iUnion fun i => (hf i).1, fun σ h => by
    rw [Set.preimage_iUnion]
    exact Set.iUnion_congr fun i => (hf i).2 σ h⟩

theorem RelStructure.fixingAlgebra_le (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    RelStructure.fixingAlgebra (S := S) A ≤
      (inferInstance : MeasurableSpace (RelStructure S (Vinfinite S))) :=
  fun _ hE => hE.1

/-- **Monotonicity**: a larger fixed set is a smaller stabilizer, hence more invariant
events. -/
theorem RelStructure.fixingAlgebra_mono {A B : Finset (Σ s : S.Srt, Vinfinite S s)} (hAB : A ⊆ B) :
    RelStructure.fixingAlgebra (S := S) A ≤ RelStructure.fixingAlgebra (S := S) B :=
  fun _ hE => ⟨hE.1, fun σ hσ => hE.2 σ ⟨hσ.1, fun v hv => hσ.2 v (hAB hv)⟩⟩

/-- **The bottom factor is the invariant σ-algebra** — near-definitional: at `A = ∅` the
fixing condition is vacuous and the stabilizer is the full finitely supported group, so
dissociation/ergodicity (R3, #106) trivializes exactly this factor. -/
theorem RelStructure.fixingAlgebra_empty :
    RelStructure.fixingAlgebra (S := S) ∅ = RelStructure.invariantAlgebra := by
  refine MeasurableSpace.ext fun E => ⟨fun hE => ⟨hE.1, fun σ hσ => hE.2 σ ⟨hσ, fun v hv =>
    absurd hv (Finset.notMem_empty v)⟩⟩, fun hE => ⟨hE.1, fun σ hσ => hE.2 σ hσ.1⟩⟩

/-! ### Transport -/

/-- Relabelings compose contravariantly (permutation product acts inner-first). -/
theorem RelStructure.relabel_comp_relabel (σ τ : ∀ _ : S.Srt, Equiv.Perm ℕ) :
    RelStructure.relabel (V := Vinfinite S) σ ∘ RelStructure.relabel τ =
      RelStructure.relabel fun s => τ s * σ s := by
  funext X
  show RelStructure.comap _ (RelStructure.comap _ X) = _
  rw [← RelStructure.comap_comp]
  rfl

theorem RelStructure.relabel_preimage_relabel_preimage
    (τ σ : ∀ _ : S.Srt, Equiv.Perm ℕ) (E : Set (RelStructure S (Vinfinite S))) :
    RelStructure.relabel τ ⁻¹' (RelStructure.relabel σ ⁻¹' E) =
      RelStructure.relabel (fun s => τ s * σ s) ⁻¹' E := by
  rw [← Set.preimage_comp, RelStructure.relabel_comp_relabel]

open scoped Classical in
/-- One-sided transport, parametric in the conjugation closure: pulling an invariant event
back along a relabeling whose conjugation carries image-stabilizers to `A`-stabilizers lands
in the fixing algebra of the image vertex set. -/
private theorem fixingAlgebra_comap_relabel_le (σ : ∀ _ : S.Srt, Equiv.Perm ℕ)
    (A : Finset (Σ s : S.Srt, Vinfinite S s))
    (hconj : ∀ τ, SortwiseFixing (S := S) (A.image (Sigma.map id fun s => ⇑(σ s))) τ →
      SortwiseFixing (S := S) A fun s => (σ s)⁻¹ * τ s * σ s) :
    MeasurableSpace.comap (RelStructure.relabel σ) (RelStructure.fixingAlgebra (S := S) A) ≤
      RelStructure.fixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))) := by
  rintro - ⟨E, hE, rfl⟩
  refine ⟨measurable_relabel σ hE.1, fun τ hτ => ?_⟩
  rw [RelStructure.relabel_preimage_relabel_preimage,
    show (fun s => τ s * σ s) = fun s => σ s * ((σ s)⁻¹ * τ s * σ s) from
      funext fun s => by group,
    ← RelStructure.relabel_preimage_relabel_preimage, hE.2 _ (hconj τ hτ)]

open scoped Classical in
/-- Two one-sided transports (for `σ` and for its inverse) assemble into the transport
equality: the inverse inclusion is pushed through `comap` composition and the collapse of
`σ⁻¹ ∘ σ` on images. -/
private theorem fixingAlgebra_comap_relabel_of_le (σ : ∀ _ : S.Srt, Equiv.Perm ℕ)
    (A : Finset (Σ s : S.Srt, Vinfinite S s))
    (h₁ : MeasurableSpace.comap (RelStructure.relabel σ)
        (RelStructure.fixingAlgebra (S := S) A) ≤
      RelStructure.fixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))))
    (h₂ : MeasurableSpace.comap (RelStructure.relabel fun s => (σ s)⁻¹)
        (RelStructure.fixingAlgebra (S := S) (A.image (Sigma.map id fun s => ⇑(σ s)))) ≤
      RelStructure.fixingAlgebra ((A.image (Sigma.map id fun s => ⇑(σ s))).image
        (Sigma.map id fun s => ⇑(σ s)⁻¹))) :
    MeasurableSpace.comap (RelStructure.relabel σ) (RelStructure.fixingAlgebra (S := S) A) =
      RelStructure.fixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))) := by
  refine le_antisymm h₁ ?_
  have himg : ((A.image (Sigma.map id fun s => ⇑(σ s))).image
      (Sigma.map id fun s => ⇑(σ s)⁻¹)) = A := by
    rw [Finset.image_image]
    refine (Finset.image_congr fun v _ => ?_).trans A.image_id
    obtain ⟨s, x⟩ := v
    show ⟨s, (σ s)⁻¹ (σ s x)⟩ = (⟨s, x⟩ : Σ s : S.Srt, Vinfinite S s)
    rw [show (σ s)⁻¹ (σ s x) = x from (σ s).symm_apply_apply x]
  rw [himg] at h₂
  have := MeasurableSpace.comap_mono (g := RelStructure.relabel (V := Vinfinite S) σ) h₂
  rwa [MeasurableSpace.comap_comp, RelStructure.relabel_comp_relabel,
    show (fun s => σ s * (σ s)⁻¹) = fun _ : S.Srt => (1 : Equiv.Perm ℕ) from
      funext fun s => mul_inv_cancel (σ s),
    show RelStructure.relabel (V := Vinfinite S) (fun _ : S.Srt => (1 : Equiv.Perm ℕ)) = id from
      rfl,
    MeasurableSpace.comap_id] at this

open scoped Classical in
/-- **Transport of the fixing σ-algebra** along a finitely supported sortwise relabeling —
an equality of pulled-back measurable spaces, not merely an event-membership equivalence:
the pullback of the `A`-fixing algebra is the fixing algebra of the image vertex set.
Stabilizers conjugate (`SortwiseFixing.conj`); the reverse inclusion is the forward one for
`σ⁻¹` transported through `comap` composition. Over infinitely many sorts the finite-support
hypothesis is genuinely necessary; under `[Fintype S.Srt]` see
`fixingAlgebra_comap_relabel_of_fintype`. -/
theorem RelStructure.fixingAlgebra_comap_relabel {σ : ∀ _ : S.Srt, Equiv.Perm ℕ}
    (hσ : SortwiseFinSupp (S := S) σ) (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    MeasurableSpace.comap (RelStructure.relabel σ) (RelStructure.fixingAlgebra (S := S) A) =
      RelStructure.fixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))) :=
  fixingAlgebra_comap_relabel_of_le σ A
    (fixingAlgebra_comap_relabel_le σ A fun _ hτ => SortwiseFixing.conj hσ hτ)
    (fixingAlgebra_comap_relabel_le _ _ fun _ hτ => SortwiseFixing.conj hσ.inv hτ)

open scoped Classical in
/-- **Transport along a sortwise permutation with finitely many active sorts**: no support bound
on `σ` is needed, since conjugation recovers a common bound on the active sorts
(`SortwiseFixing.conj_of_finiteActive`). -/
theorem RelStructure.fixingAlgebra_comap_relabel_of_finiteActive
    {σ : ∀ _ : S.Srt, Equiv.Perm ℕ} (hσ : SortwiseFiniteActive (S := S) σ)
    (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    MeasurableSpace.comap (RelStructure.relabel σ) (RelStructure.fixingAlgebra (S := S) A) =
      RelStructure.fixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))) :=
  fixingAlgebra_comap_relabel_of_le σ A
    (fixingAlgebra_comap_relabel_le σ A fun _ hτ => SortwiseFixing.conj_of_finiteActive hσ hτ)
    (fixingAlgebra_comap_relabel_le _ _ fun _ hτ =>
      SortwiseFixing.conj_of_finiteActive hσ.inv hτ)

open scoped Classical in
/-- **Transport under finitely many sorts holds for an arbitrary sortwise permutation
family**: the finite-active statement at `T = univ`. -/
theorem RelStructure.fixingAlgebra_comap_relabel_of_fintype [Fintype S.Srt]
    (σ : ∀ _ : S.Srt, Equiv.Perm ℕ) (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    MeasurableSpace.comap (RelStructure.relabel σ) (RelStructure.fixingAlgebra (S := S) A) =
      RelStructure.fixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))) :=
  RelStructure.fixingAlgebra_comap_relabel_of_finiteActive (SortwiseFiniteActive.of_fintype σ) A

end RelSignature
