/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Graphon.RelInvariantAction

/-!
# The raw fixing σ-algebras of finite tagged vertex sets (R4 converse piece 2a, #107)

The **law-independent** factor-algebra layer of the converse representation theorem: for a
finite set `A` of tagged vertices, the σ-algebra of events invariant under every finitely
supported sortwise permutation **fixing every tagged vertex of `A`** — the `A`-relativized
`RelStructure.invariantAlgebra`. Crucially this is *not* "generated by the relation
coordinates inside `A`" (that loses hidden vertex information — a vertex latent carries more
than the relations observed at the vertex); the invariance definition captures everything
the ambient randomness outside `A` cannot move.

Everything here is raw and measure-free — **no completions, no conditional expectations, no
law**. Per the #107 design checkpoint: conditional independence under a dissociated law and
the standard-Borel factor realizations (both stated *modulo the law*) are deliberately
separate, later PRs. The intended core statement (next PR), with
`[Countable S.Rel]` supplying `StandardBorelSpace (RelStructure S (Vinfinite S))`:
`CondIndep (fixingAlgebra (A ∩ B)) (fixingAlgebra A) (fixingAlgebra B)
(fixingAlgebra_le _) M.law` for dissociated `M`. Sanity specializations: at `A = B`, and
likewise at `A = ∅` or `B = ∅`, one outer algebra *equals* the conditioning algebra
`fixingAlgebra (A ∩ B)`, so the statement is tautological — conditional independence of an
algebra from anything given itself — independently of dissociation; the dissociation
content is at disjoint nonempty `A, B`.

* `RelSignature.SortwiseFixing` — the `A`-fixing stabilizer (finitely supported + fixes
  `A` pointwise), closed under `1`, `*`, `⁻¹`, and conjugation (`SortwiseFixing.conj`);
* `RelStructure.fixingAlgebra` — the raw fixing σ-algebra, with `fixingAlgebra_le`;
* `RelStructure.fixingAlgebra_mono` — monotone: `A ⊆ B → fixingAlgebra A ≤ fixingAlgebra B`
  (a larger fixed set is a smaller stabilizer, hence more invariant events);
* `RelStructure.fixingAlgebra_empty` — `fixingAlgebra ∅ = invariantAlgebra`
  (near-definitional: the same finitary action);
* `RelStructure.fixingAlgebra_comap_relabel` — **transport**: pulling back along a finitely
  supported relabeling is an *equality of measurable spaces*
  `comap (relabel σ) (fixingAlgebra A) = fixingAlgebra (image σ A)`, by conjugating
  stabilizers.
-/

open Function

namespace RelSignature

variable {S : RelSignature}

/-! ### The fixing stabilizer -/

/-- **The `A`-fixing stabilizer**: a sortwise permutation family with common finite support
fixing every tagged vertex of `A`. At `A = ∅` this is `SortwiseFinSupp` — the acting group
of `RelStructure.invariantAlgebra`. -/
def SortwiseFixing (A : Finset (Σ s : S.Srt, Vinfinite S s)) (σ : ∀ _ : S.Srt, Equiv.Perm ℕ) : Prop :=
  SortwiseFinSupp (S := S) σ ∧ ∀ v ∈ A, σ v.1 v.2 = v.2

namespace SortwiseFixing

variable {A : Finset (Σ s : S.Srt, Vinfinite S s)} {σ τ : ∀ _ : S.Srt, Equiv.Perm ℕ}

theorem one : SortwiseFixing (S := S) A fun _ => 1 :=
  ⟨SortwiseFinSupp.one, fun _ _ => rfl⟩

theorem mul (hσ : SortwiseFixing (S := S) A σ) (hτ : SortwiseFixing (S := S) A τ) :
    SortwiseFixing (S := S) A fun s => σ s * τ s :=
  ⟨hσ.1.mul hτ.1, fun v hv => by
    show σ v.1 (τ v.1 v.2) = v.2
    rw [hτ.2 v hv, hσ.2 v hv]⟩

theorem inv (hσ : SortwiseFixing (S := S) A σ) :
    SortwiseFixing (S := S) A fun s => (σ s)⁻¹ :=
  ⟨hσ.1.inv, fun v hv => by
    conv_lhs => rw [← hσ.2 v hv]
    exact (σ v.1).symm_apply_apply v.2⟩

open scoped Classical in
/-- **Conjugation moves the fixed set**: conjugating a stabilizer of the image vertex set by
`σ` gives a stabilizer of `A` — the group-theoretic heart of the transport theorem. Finite
support survives because a common bound for `σ` and `τ` bounds the conjugate. -/
theorem conj (hσ : SortwiseFinSupp (S := S) σ)
    (hτ : SortwiseFixing (S := S) (A.image (Sigma.map id fun s => ⇑(σ s))) τ) :
    SortwiseFixing (S := S) A fun s => (σ s)⁻¹ * τ s * σ s := by
  constructor
  · obtain ⟨N, hN⟩ := hσ
    obtain ⟨M, hM⟩ := hτ.1
    refine ⟨max N M, fun s x hx => ?_⟩
    have h1 : σ s x = x := hN s x (le_trans (le_max_left _ _) hx)
    show (σ s)⁻¹ (τ s (σ s x)) = x
    rw [h1, hM s x (le_trans (le_max_right _ _) hx)]
    conv_lhs => rw [← h1]
    exact (σ s).symm_apply_apply x
  · rintro ⟨s, x⟩ hv
    have himg := hτ.2 (Sigma.map id (fun s => ⇑(σ s)) ⟨s, x⟩) (Finset.mem_image_of_mem _ hv)
    show (σ s)⁻¹ (τ s (σ s x)) = x
    rw [show τ s (σ s x) = σ s x from himg]
    exact (σ s).symm_apply_apply x

end SortwiseFixing

/-! ### The raw fixing σ-algebra -/

/-- **The raw fixing σ-algebra** of a finite tagged vertex set `A`: measurable events
invariant under every finitely supported sortwise relabeling fixing every tagged vertex of
`A`. Law-independent by construction — completions, conditional expectations, and mod-null
factor realizations explicitly carry a law and live in later layers. -/
@[implicit_reducible]
def RelStructure.fixingAlgebra (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    MeasurableSpace (RelStructure S (Vinfinite S)) where
  MeasurableSet' E := MeasurableSet E ∧
    ∀ σ, SortwiseFixing (S := S) A σ → RelStructure.relabel σ ⁻¹' E = E
  measurableSet_empty := ⟨MeasurableSet.empty, fun _ _ => Set.preimage_empty⟩
  measurableSet_compl := fun E hE => ⟨hE.1.compl, fun σ h => by
    rw [Set.preimage_compl, hE.2 σ h]⟩
  measurableSet_iUnion := fun f hf => ⟨MeasurableSet.iUnion fun i => (hf i).1, fun σ h => by
    rw [Set.preimage_iUnion]
    exact Set.iUnion_congr fun i => (hf i).2 σ h⟩

theorem RelStructure.fixingAlgebra_le (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    RelStructure.fixingAlgebra (S := S) A ≤
      (inferInstance : MeasurableSpace (RelStructure S (Vinfinite S))) :=
  fun _ hE => hE.1

/-- **Monotonicity**: a larger fixed set is a smaller stabilizer, hence more invariant
events. -/
theorem RelStructure.fixingAlgebra_mono {A B : Finset (Σ s : S.Srt, Vinfinite S s)} (hAB : A ⊆ B) :
    RelStructure.fixingAlgebra (S := S) A ≤ RelStructure.fixingAlgebra (S := S) B :=
  fun _ hE => ⟨hE.1, fun σ hσ => hE.2 σ ⟨hσ.1, fun v hv => hσ.2 v (hAB hv)⟩⟩

/-- **The bottom factor is the invariant σ-algebra** — near-definitional: at `A = ∅` the
fixing condition is vacuous and the stabilizer is the full finitely supported group, so
dissociation/ergodicity (R3, #106) trivializes exactly this factor. -/
theorem RelStructure.fixingAlgebra_empty :
    RelStructure.fixingAlgebra (S := S) ∅ = RelStructure.invariantAlgebra := by
  refine MeasurableSpace.ext fun E => ⟨fun hE => ⟨hE.1, fun σ hσ => hE.2 σ ⟨hσ, fun v hv =>
    absurd hv (Finset.notMem_empty v)⟩⟩, fun hE => ⟨hE.1, fun σ hσ => hE.2 σ hσ.1⟩⟩

/-! ### Transport -/

/-- Relabelings compose contravariantly (permutation product acts inner-first). -/
theorem RelStructure.relabel_comp_relabel (σ τ : ∀ _ : S.Srt, Equiv.Perm ℕ) :
    RelStructure.relabel (V := Vinfinite S) σ ∘ RelStructure.relabel τ =
      RelStructure.relabel fun s => τ s * σ s := by
  funext X
  show RelStructure.comap _ (RelStructure.comap _ X) = _
  rw [← RelStructure.comap_comp]
  rfl

theorem RelStructure.relabel_preimage_relabel_preimage
    (τ σ : ∀ _ : S.Srt, Equiv.Perm ℕ) (E : Set (RelStructure S (Vinfinite S))) :
    RelStructure.relabel τ ⁻¹' (RelStructure.relabel σ ⁻¹' E) =
      RelStructure.relabel (fun s => τ s * σ s) ⁻¹' E := by
  rw [← Set.preimage_comp, RelStructure.relabel_comp_relabel]

open scoped Classical in
/-- One-sided transport: pulling an invariant event back along a finitely supported
relabeling lands in the fixing algebra of the image vertex set, by conjugating the
stabilizer through `SortwiseFixing.conj`. -/
private theorem fixingAlgebra_comap_relabel_le {σ : ∀ _ : S.Srt, Equiv.Perm ℕ}
    (hσ : SortwiseFinSupp (S := S) σ) (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    MeasurableSpace.comap (RelStructure.relabel σ) (RelStructure.fixingAlgebra (S := S) A) ≤
      RelStructure.fixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))) := by
  rintro - ⟨E, hE, rfl⟩
  refine ⟨measurable_relabel σ hE.1, fun τ hτ => ?_⟩
  rw [RelStructure.relabel_preimage_relabel_preimage,
    show (fun s => τ s * σ s) = fun s => σ s * ((σ s)⁻¹ * τ s * σ s) from
      funext fun s => by group,
    ← RelStructure.relabel_preimage_relabel_preimage, hE.2 _ (SortwiseFixing.conj hσ hτ)]

open scoped Classical in
/-- **Transport of the fixing σ-algebra** along a finitely supported sortwise relabeling —
an equality of pulled-back measurable spaces, not merely an event-membership equivalence:
the pullback of the `A`-fixing algebra is the fixing algebra of the image vertex set.
Stabilizers conjugate (`SortwiseFixing.conj`); the reverse inclusion is the forward one for
`σ⁻¹` transported through `comap` composition. -/
theorem RelStructure.fixingAlgebra_comap_relabel {σ : ∀ _ : S.Srt, Equiv.Perm ℕ}
    (hσ : SortwiseFinSupp (S := S) σ) (A : Finset (Σ s : S.Srt, Vinfinite S s)) :
    MeasurableSpace.comap (RelStructure.relabel σ) (RelStructure.fixingAlgebra (S := S) A) =
      RelStructure.fixingAlgebra (A.image (Sigma.map id fun s => ⇑(σ s))) := by
  refine le_antisymm (fixingAlgebra_comap_relabel_le hσ A) ?_
  have hback := fixingAlgebra_comap_relabel_le (S := S) hσ.inv
    (A.image (Sigma.map id fun s => ⇑(σ s)))
  have himg : ((A.image (Sigma.map id fun s => ⇑(σ s))).image
      (Sigma.map id fun s => ⇑(σ s)⁻¹)) = A := by
    rw [Finset.image_image]
    refine (Finset.image_congr fun v _ => ?_).trans A.image_id
    obtain ⟨s, x⟩ := v
    show ⟨s, (σ s)⁻¹ (σ s x)⟩ = (⟨s, x⟩ : Σ s : S.Srt, Vinfinite S s)
    rw [show (σ s)⁻¹ (σ s x) = x from (σ s).symm_apply_apply x]
  rw [himg] at hback
  have := MeasurableSpace.comap_mono (g := RelStructure.relabel (V := Vinfinite S) σ) hback
  rwa [MeasurableSpace.comap_comp, RelStructure.relabel_comp_relabel,
    show (fun s => σ s * (σ s)⁻¹) = fun _ : S.Srt => (1 : Equiv.Perm ℕ) from
      funext fun s => mul_inv_cancel (σ s),
    show RelStructure.relabel (V := Vinfinite S) (fun _ : S.Srt => (1 : Equiv.Perm ℕ)) = id from
      rfl,
    MeasurableSpace.comap_id] at this

end RelSignature
