/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Graphon.RelCoherentBasis
import Graphon.RelRankAlgebra

/-!
# The lower-rank factor of a coherent basis (R4 converse piece 3, #107)

The factor coordinates whose anchors have cardinality below `n`: the structural object the
rank induction conditions on.

## Why the factor, not the latents

The conditioning factor must be described by the *basis coordinates*, not by the latents that
will eventually encode them. A latent normally carries randomness beyond the factor it
represents — already `1_{U < p}` generates strictly less than `U` — so a σ-algebra generated by
latents is typically strictly larger than the factor. Everything here is therefore stated about
`lowerFactorMap`, and the coupling to latents is deliberately absent: it belongs to the
augmented-induction layer, which should consume a settled lower-factor API rather than be mixed
with it.

## The generation statement

Only

`comap (lowerFactorMap n) inferInstance ≤ lowerRankAlgebra n`

together with an eventwise mod-null converse. **No raw equality of measurable spaces** — the
same discipline as everywhere else in this layer, and for the same reason.

`LowerIndex n` is not closed under the Boolean operations: two small anchors can combine to a
large one. That is not a defect and no closure should be engineered — the product σ-algebra on
`LowerFactorSpace n` still contains Boolean combinations of the coordinates.
-/

open MeasureTheory MeasurableSpace

namespace RelSignature

namespace CoherentBasis

universe u

variable {S : RelSignature.{u}} {M : InfiniteRelExchangeableLaw S} (B : CoherentBasis M)

/-! ### The lower-rank index and factor space -/

/-- **The indices of rank below `n`**: basis coordinates whose anchor has cardinality `< n`. -/
def LowerIndex (n : ℕ) := {i : B.ι // (B.anchor i).card < n}

instance (n : ℕ) : Countable (B.LowerIndex n) := Subtype.countable

/-- At rank bound `0` there are no such indices. -/
instance : IsEmpty (B.LowerIndex 0) := ⟨fun i => absurd i.2 (by omega)⟩

/-- **The lower-rank factor space**, standard Borel since the index is countable. -/
abbrev LowerFactorSpace (n : ℕ) := B.LowerIndex n → Bool

instance (n : ℕ) : StandardBorelSpace (B.LowerFactorSpace n) := inferInstance

/-- At rank bound `0` the factor space is a single point. -/
instance : Subsingleton (B.LowerFactorSpace 0) :=
  ⟨fun _ _ => funext fun i => (IsEmpty.false i).elim⟩

open scoped Classical in
/-- **The lower-rank factor map**: evaluate every basis event anchored below rank `n`. -/
noncomputable def lowerFactorMap (n : ℕ) :
    RelStructure S (Vinfinite S) → B.LowerFactorSpace n :=
  fun X i => decide (X ∈ B.event i.1)

/-! ### Measurability -/

open scoped Classical in
/-- The lower-rank factor map is measurable for `lowerRankAlgebra n`: each coordinate is the
indicator of an event whose anchor has rank `< n`. -/
theorem measurable_lowerFactorMap (n : ℕ) :
    Measurable[RelStructure.lowerRankAlgebra (S := S) n] (B.lowerFactorMap n) := by
  classical
  letI : MeasurableSpace (RelStructure S (Vinfinite S)) :=
    RelStructure.lowerRankAlgebra (S := S) n
  refine measurable_pi_iff.mpr fun i => measurable_to_bool ?_
  have hmem : MeasurableSet[RelStructure.lowerRankAlgebra (S := S) n] (B.event i.1) :=
    RelStructure.fixingAlgebra_le_lowerRankAlgebra i.2 _ (B.event_mem i.1)
  convert hmem using 1
  ext X
  simp [lowerFactorMap]

/-- **The pullback lands inside the conditioning factor.** This is one half of the generation
statement; the converse is eventwise and modulo the law. -/
theorem comap_lowerFactorMap_le (n : ℕ) :
    MeasurableSpace.comap (B.lowerFactorMap n) inferInstance ≤
      RelStructure.lowerRankAlgebra (S := S) n :=
  (B.measurable_lowerFactorMap n).comap_le

/-- The lower-rank factor map is measurable for the ambient σ-algebra too. -/
theorem measurable_lowerFactorMap' (n : ℕ) : Measurable (B.lowerFactorMap n) :=
  (B.measurable_lowerFactorMap n).mono (RelStructure.lowerRankAlgebra_le n) le_rfl

/-! ### Rank nesting -/

/-- The index embedding for `n ≤ m`: a smaller rank bound admits fewer coordinates. -/
def lowerIndexEmbedding {n m : ℕ} (h : n ≤ m) : B.LowerIndex n → B.LowerIndex m :=
  fun i => ⟨i.1, lt_of_lt_of_le i.2 h⟩

/-- The factor projection for `n ≤ m`: ordinary coordinate restriction. -/
def lowerFactorProjection {n m : ℕ} (h : n ≤ m) :
    B.LowerFactorSpace m → B.LowerFactorSpace n :=
  fun f => f ∘ B.lowerIndexEmbedding h

theorem measurable_lowerFactorProjection {n m : ℕ} (h : n ≤ m) :
    Measurable (B.lowerFactorProjection h) :=
  measurable_pi_lambda _ fun _ => measurable_pi_apply _

open scoped Classical in
/-- **The projection is compatible with the factor maps** — definitional, since both sides read
the same coordinates. -/
theorem lowerFactorProjection_lowerFactorMap {n m : ℕ} (h : n ≤ m) :
    B.lowerFactorProjection h ∘ B.lowerFactorMap m = B.lowerFactorMap n := rfl

/-- **The projection cocycle**, likewise definitional. -/
theorem lowerFactorProjection_comp {n m k : ℕ} (hnm : n ≤ m) (hmk : m ≤ k) :
    B.lowerFactorProjection hnm ∘ B.lowerFactorProjection hmk =
      B.lowerFactorProjection (hnm.trans hmk) := rfl

/-! ### Restriction to a single support -/

/-- Every coordinate anchored inside `A` has rank below `n`, when `A` itself does. -/
def basisIndexToLowerIndex {A : Finset (Σ s : S.Srt, Vinfinite S s)} {n : ℕ}
    (hA : A.card < n) : B.BasisIndex A → B.LowerIndex n :=
  fun i => ⟨i.1, lt_of_le_of_lt (Finset.card_le_card i.2) hA⟩

/-- **The finite-factor projection**: restrict the lower-rank factor to the coordinates of a
single support of rank `< n`. This is the device that lets the generation argument work support
by support, rather than trying to assemble representatives through the `iSup`. -/
def lowerToFactorProjection {A : Finset (Σ s : S.Srt, Vinfinite S s)} {n : ℕ}
    (hA : A.card < n) : B.LowerFactorSpace n → B.FactorSpace A :=
  fun f => f ∘ B.basisIndexToLowerIndex hA

theorem measurable_lowerToFactorProjection {A : Finset (Σ s : S.Srt, Vinfinite S s)} {n : ℕ}
    (hA : A.card < n) : Measurable (B.lowerToFactorProjection hA) :=
  measurable_pi_lambda _ fun _ => measurable_pi_apply _

open scoped Classical in
/-- **Compatibility with the single-support factor map**, definitional: reading the `A`-anchored
coordinates of the lower-rank factor *is* the factor map at `A`. -/
theorem lowerToFactorProjection_lowerFactorMap {A : Finset (Σ s : S.Srt, Vinfinite S s)} {n : ℕ}
    (hA : A.card < n) :
    B.lowerToFactorProjection hA ∘ B.lowerFactorMap n = B.factorMap A := rfl

end CoherentBasis

end RelSignature
