/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Graphon.ForMathlib.RelativeFactorCoupling
import Graphon.KernelRandomization

/-!
# Coupling a factor to a uniform latent (R4 converse piece 3, #107)

The specialization of `ProbabilityTheory.relativeFactorCoupling` in which the second space is the
project's uniform source: given a factor map `q : Ω → Z` of a probability measure `μ`, there is a
coupling of `μ` with `uniform01` on `Ω × ℝ` whose second coordinate is uniform, whose first has
law `μ`, in which the latent *resolves* the factor, and in which the latent tells nothing further
about `Ω`.

This is the narrow randomization step the rankwise recursion needs, and it runs in the direction
that `Graphon.KernelRandomization` does not: that module manufactures a variable with a prescribed
law *out of* a uniform, whereas here a uniform must be manufactured *alongside* an already-given
variable. The only uniform-specific input is `Measure.exists_measurable_map_eq_uniform01` (#140),
which supplies the coding map `f : ℝ → Z` matching the two factor laws; everything after that is
the generic relative joining.

## Contents

* `ProbabilityTheory.exists_relativeFactorCoupling_uniform01` — the wrapper: a measurable coding
  map together with all five properties of the resulting coupling.
-/

open MeasureTheory ProbabilityTheory

namespace ProbabilityTheory

variable {Ω Z : Type*} [MeasurableSpace Ω] [StandardBorelSpace Ω] [Nonempty Ω]
  [MeasurableSpace Z] [StandardBorelSpace Z] [Nonempty Z]

/-- **Every factor of a probability measure can be coupled to a uniform latent.** The coding map
`f` comes from the randomization adapter; the coupling is the relatively independent joining of
`μ` and `uniform01` over the common `Z`-factor, and it satisfies, in order: it is a probability
measure; its first marginal is `μ`; its second marginal is `uniform01`; the latent resolves the
factor, `q X = f ξ` a.s.; and the two coordinates are conditionally independent given the factor
read off the first coordinate.

The conditioning σ-algebra is generated by `q ∘ Prod.fst`, a variable on the coupling space
itself, rather than by the disintegration variable the construction integrates out. Conditional
independence of the latent from any coarser function of the first coordinate follows by
measurable composition. -/
theorem exists_relativeFactorCoupling_uniform01 (μ : Measure Ω) [IsProbabilityMeasure μ]
    {q : Ω → Z} (hq : Measurable q) :
    ∃ f : ℝ → Z, Measurable f ∧
      IsProbabilityMeasure (relativeFactorCoupling μ uniform01 q f) ∧
      (relativeFactorCoupling μ uniform01 q f).map Prod.fst = μ ∧
      (relativeFactorCoupling μ uniform01 q f).map Prod.snd = uniform01 ∧
      q ∘ Prod.fst =ᵐ[relativeFactorCoupling μ uniform01 q f] f ∘ Prod.snd ∧
      CondIndepFun (MeasurableSpace.comap (q ∘ Prod.fst) inferInstance)
        (hq.comp measurable_fst).comap_le Prod.fst Prod.snd
        (relativeFactorCoupling μ uniform01 q f) := by
  haveI : IsProbabilityMeasure (μ.map q) := Measure.isProbabilityMeasure_map hq.aemeasurable
  obtain ⟨f, hf, hfq⟩ := (μ.map q).exists_measurable_map_eq_uniform01
  exact ⟨f, hf, isProbabilityMeasure_relativeFactorCoupling hq,
    map_fst_relativeFactorCoupling hq, map_snd_relativeFactorCoupling hf hfq,
    comp_fst_ae_eq_comp_snd_relativeFactorCoupling hq hf hfq,
    condIndepFun_fst_snd_relativeFactorCoupling hq hf hfq⟩

end ProbabilityTheory
