#!/usr/bin/env python3
"""
Test whether the 2-labeled evaluation span generated by left/right adjacency
from the edge function matches the number of Aut(B,W)-orbits on pairs.

For a weighted graph (B, W) on T vertices:
- Edge function: e(i,j) = B(i,j), viewed as a vector in R^{T^2}
- Left adjacency:  (L f)(i,j) = sum_m W(m) * B(i,m) * f(m,j)
- Right adjacency: (R f)(i,j) = sum_m W(m) * f(i,m) * B(m,j)
- Span: closure of {e} under L and R
- Orbits: Aut(B,W)-orbits on {(i,j) : i,j in Fin T}

CT-1 predicts: dim(span) = number of orbits.
"""

import numpy as np
from itertools import permutations
from typing import NamedTuple


class TestCase(NamedTuple):
    name: str
    B: np.ndarray  # T x T symmetric matrix with entries in [0,1]
    W: np.ndarray  # T-vector of positive weights


def left_adj(B: np.ndarray, W: np.ndarray, f: np.ndarray) -> np.ndarray:
    """(L f)(i,j) = sum_m W(m) * B(i,m) * f(m,j)"""
    T = B.shape[0]
    result = np.zeros((T, T))
    for i in range(T):
        for j in range(T):
            result[i, j] = sum(W[m] * B[i, m] * f[m, j] for m in range(T))
    return result


def right_adj(B: np.ndarray, W: np.ndarray, f: np.ndarray) -> np.ndarray:
    """(R f)(i,j) = sum_m W(m) * f(i,m) * B(m,j)"""
    T = B.shape[0]
    result = np.zeros((T, T))
    for i in range(T):
        for j in range(T):
            result[i, j] = sum(W[m] * f[i, m] * B[m, j] for m in range(T))
    return result


def compute_span(B: np.ndarray, W: np.ndarray, tol: float = 1e-10,
                  include_mult: bool = True) -> int:
    """Compute dimension of span generated by {1, edge} under L, R, and pointwise mult.

    Generators: 1(i,j) = 1 (empty 2-labeled graph), e(i,j) = B(i,j) (edge graph).
    Operations: left adjacency, right adjacency, pointwise multiplication (= gluing).
    """
    T = B.shape[0]
    ones = np.ones(T * T)
    basis = [ones, B.flatten()]

    # Remove redundant initial basis if 1 and B are proportional (unlikely)
    if np.linalg.matrix_rank(np.vstack(basis), tol=tol) < 2:
        basis = [ones]

    def try_add(v: np.ndarray) -> bool:
        """Try to add v to basis. Return True if it increased the dimension."""
        mat = np.vstack(basis + [v])
        new_rank = np.linalg.matrix_rank(mat, tol=tol)
        if new_rank > len(basis):
            basis.append(v)
            return True
        return False

    # Iteratively apply L, R, and pointwise multiplication until stable
    changed = True
    while changed:
        changed = False
        current_size = len(basis)
        for idx in range(current_size):
            f = basis[idx].reshape(T, T)
            lf = left_adj(B, W, f).flatten()
            rf = right_adj(B, W, f).flatten()
            if try_add(lf):
                changed = True
            if try_add(rf):
                changed = True
        if include_mult:
            current_size = len(basis)
            for i_idx in range(current_size):
                for j_idx in range(i_idx, current_size):
                    prod = basis[i_idx] * basis[j_idx]  # pointwise
                    if try_add(prod):
                        changed = True

    return len(basis)


def compute_span_no_mult(B: np.ndarray, W: np.ndarray, tol: float = 1e-10) -> int:
    """Span under L, R only (no pointwise multiplication) — for comparison."""
    return compute_span(B, W, tol=tol, include_mult=False)


def compute_automorphisms(B: np.ndarray, W: np.ndarray, tol: float = 1e-10):
    """Find all (B,W)-automorphisms: permutations pi with W(pi(i))=W(i) and B(pi(i),pi(j))=B(i,j)."""
    T = B.shape[0]
    auts = []
    for perm in permutations(range(T)):
        # Check weight preservation
        if not all(abs(W[perm[i]] - W[i]) < tol for i in range(T)):
            continue
        # Check matrix preservation
        ok = True
        for i in range(T):
            for j in range(T):
                if abs(B[perm[i]][perm[j]] - B[i][j]) > tol:
                    ok = False
                    break
            if not ok:
                break
        if ok:
            auts.append(perm)
    return auts


def count_orbits(auts: list, T: int) -> int:
    """Count orbits of aut group on T x T pairs (Burnside's lemma)."""
    total_fixed = 0
    for perm in auts:
        fixed = sum(1 for i in range(T) for j in range(T)
                    if perm[i] == i and perm[j] == j)
        total_fixed += fixed
    return total_fixed // len(auts)


def count_orbits_direct(auts: list, T: int) -> int:
    """Count orbits by direct enumeration (cross-check)."""
    visited = set()
    orbits = 0
    for i in range(T):
        for j in range(T):
            if (i, j) not in visited:
                orbits += 1
                for perm in auts:
                    visited.add((perm[i], perm[j]))
    return orbits


# ---- Test cases ----

def make_test_cases():
    cases = []

    # T=2, trivial automorphism (asymmetric weights)
    cases.append(TestCase(
        name="T=2, trivial Aut (distinct weights)",
        B=np.array([[0.3, 0.7], [0.7, 0.5]]),
        W=np.array([0.6, 0.4]),
    ))

    # T=2, nontrivial automorphism (equal weights, symmetric B)
    cases.append(TestCase(
        name="T=2, Z/2 Aut (equal weights, B(0,0)=B(1,1))",
        B=np.array([[0.3, 0.7], [0.7, 0.3]]),
        W=np.array([0.5, 0.5]),
    ))

    # T=2, nontrivial Aut, diagonal differs
    cases.append(TestCase(
        name="T=2, trivial Aut (equal weights, B(0,0)!=B(1,1))",
        B=np.array([[0.3, 0.7], [0.7, 0.5]]),
        W=np.array([0.5, 0.5]),
    ))

    # T=3, trivial automorphism
    cases.append(TestCase(
        name="T=3, trivial Aut (generic)",
        B=np.array([[0.1, 0.2, 0.3],
                     [0.2, 0.4, 0.5],
                     [0.3, 0.5, 0.6]]),
        W=np.array([0.3, 0.3, 0.4]),
    ))

    # T=3, S3 automorphism (complete graph with equal weights)
    cases.append(TestCase(
        name="T=3, S3 Aut (constant off-diag, equal weights)",
        B=np.array([[0.2, 0.8, 0.8],
                     [0.8, 0.2, 0.8],
                     [0.8, 0.8, 0.2]]),
        W=np.array([1/3, 1/3, 1/3]),
    ))

    # T=3, Z/2 automorphism (swap 0,1; vertex 2 fixed)
    cases.append(TestCase(
        name="T=3, Z/2 Aut (swap 0<->1, vertex 2 fixed)",
        B=np.array([[0.3, 0.7, 0.5],
                     [0.7, 0.3, 0.5],
                     [0.5, 0.5, 0.6]]),
        W=np.array([0.4, 0.4, 0.2]),
    ))

    # T=4, trivial automorphism
    cases.append(TestCase(
        name="T=4, trivial Aut (generic)",
        B=np.array([[0.1, 0.2, 0.3, 0.4],
                     [0.2, 0.5, 0.6, 0.7],
                     [0.3, 0.6, 0.8, 0.9],
                     [0.4, 0.7, 0.9, 0.2]]),
        W=np.array([0.1, 0.2, 0.3, 0.4]),
    ))

    # T=4, Z/2 x Z/2 automorphism (bipartite-like blocks)
    cases.append(TestCase(
        name="T=4, Z/2xZ/2 Aut (block structure)",
        B=np.array([[0.3, 0.7, 0.5, 0.5],
                     [0.7, 0.3, 0.5, 0.5],
                     [0.5, 0.5, 0.4, 0.6],
                     [0.5, 0.5, 0.6, 0.4]]),
        W=np.array([0.25, 0.25, 0.25, 0.25]),
    ))

    # T=4, S3 acting on {0,1,2}, vertex 3 fixed
    cases.append(TestCase(
        name="T=4, S3 Aut (vertices 0,1,2 symmetric, 3 fixed)",
        B=np.array([[0.2, 0.8, 0.8, 0.5],
                     [0.8, 0.2, 0.8, 0.5],
                     [0.8, 0.8, 0.2, 0.5],
                     [0.5, 0.5, 0.5, 0.3]]),
        W=np.array([0.25, 0.25, 0.25, 0.25]),
    ))

    return cases


def enumerate_simple_graphs(n_vertices: int):
    """Enumerate all simple graphs on Fin(n_vertices) as adjacency matrices."""
    # Edges are unordered pairs {i,j} with i < j. There are n*(n-1)/2 possible edges.
    n_edges = n_vertices * (n_vertices - 1) // 2
    edges = [(i, j) for i in range(n_vertices) for j in range(i + 1, n_vertices)]
    for mask in range(1 << n_edges):
        adj = np.zeros((n_vertices, n_vertices), dtype=int)
        for bit, (i, j) in enumerate(edges):
            if mask & (1 << bit):
                adj[i][j] = 1
                adj[j][i] = 1
        yield adj


def labeled_eval2(n_unlabeled: int, adj: np.ndarray, B: np.ndarray, W: np.ndarray,
                  i: int, j: int) -> float:
    """Compute labeledEval2 for a graph on Fin(n_unlabeled + 2) with labels 0->i, 1->j.

    Sum over all colorings sigma : Fin(n_unlabeled) -> Fin(T) of unlabeled vertices.
    """
    T = B.shape[0]
    n = n_unlabeled
    total = 0.0

    # Iterate over all colorings of unlabeled vertices
    for coloring_idx in range(T ** n):
        # Decode coloring
        sigma = []
        idx = coloring_idx
        for _ in range(n):
            sigma.append(idx % T)
            idx //= T

        # Full coloring: tau(0)=i, tau(1)=j, tau(2+v)=sigma[v]
        tau = [i, j] + sigma

        # Weight product: prod over unlabeled vertices
        weight = 1.0
        for v in range(n):
            weight *= W[sigma[v]]

        # Edge product: prod over edges of the graph
        edge_prod = 1.0
        n_verts = n + 2
        for u in range(n_verts):
            for v in range(u + 1, n_verts):
                if adj[u][v]:
                    edge_prod *= B[tau[u]][tau[v]]

        total += weight * edge_prod
    return total


def compute_graph_eval_span(B: np.ndarray, W: np.ndarray, max_unlabeled: int = 3,
                            tol: float = 1e-10) -> int:
    """Compute dimension of span of actual simple-graph 2-labeled evaluations.

    Enumerates all 2-labeled simple graphs with up to max_unlabeled unlabeled vertices.
    """
    T = B.shape[0]
    vectors = []

    for n in range(max_unlabeled + 1):
        n_verts = n + 2
        for adj in enumerate_simple_graphs(n_verts):
            # Compute the evaluation vector (i,j) -> labeledEval2(n, adj, B, W, i, j)
            vec = np.zeros(T * T)
            for i in range(T):
                for j in range(T):
                    vec[i * T + j] = labeled_eval2(n, adj, B, W, i, j)
            vectors.append(vec)

    if not vectors:
        return 0
    mat = np.vstack(vectors)
    return np.linalg.matrix_rank(mat, tol=tol)


def run_tests():
    cases = make_test_cases()
    all_pass = True

    for tc in cases:
        T = tc.B.shape[0]
        assert tc.B.shape == (T, T), f"B must be square"
        assert len(tc.W) == T, f"W must have length T"
        assert np.allclose(tc.B, tc.B.T), f"B must be symmetric"

        auts = compute_automorphisms(tc.B, tc.W)
        n_orbits_burnside = count_orbits(auts, T)
        n_orbits_direct = count_orbits_direct(auts, T)
        assert n_orbits_burnside == n_orbits_direct, \
            f"Burnside/direct orbit count mismatch: {n_orbits_burnside} vs {n_orbits_direct}"

        span_dim = compute_span(tc.B, tc.W)
        span_dim_no_mult = compute_span_no_mult(tc.B, tc.W)

        # Actual graph evaluation span (up to 2 unlabeled vertices for speed)
        max_unlab = 2 if T <= 3 else 2
        graph_span = compute_graph_eval_span(tc.B, tc.W, max_unlabeled=max_unlab)

        status_alg = "PASS" if span_dim == n_orbits_direct else "FAIL"
        status_graph = "PASS" if graph_span == n_orbits_direct else "FAIL"
        if status_alg == "FAIL" or status_graph == "FAIL":
            all_pass = False

        print(f"[alg:{status_alg} graph:{status_graph}] {tc.name}")
        print(f"       T={T}  |Aut|={len(auts)}  orbits={n_orbits_direct}"
              f"  span(L,R,*)={span_dim}  span(L,R)={span_dim_no_mult}"
              f"  graphEval(≤{max_unlab})={graph_span}")
        if status_alg == "FAIL":
            print(f"       *** ALG MISMATCH ***")
        if status_graph == "FAIL":
            print(f"       *** GRAPH EVAL MISMATCH (need more unlabeled?) ***")
        print()

    if all_pass:
        print("ALL TESTS PASSED")
    else:
        print("SOME TESTS FAILED")
    return all_pass


if __name__ == "__main__":
    run_tests()
