import Graphon
/-! CI axiom audit: the load-bearing declarations below must use only axioms from the
allowed set {propext, Classical.choice, Quot.sound} — in particular no `sorryAx` and no
custom axioms. Target list and policy: `scripts/check_census_and_axioms.py`
(and `docs/post-r3-mainline-completion-plan.md` §4.4). -/
#print axioms Graphon.MeasureIso.atomless_standardBorel_mod0MeasureIso_unitInterval
#print axioms Graphon.MeasureIso.Mod0MeasureIso.toMeasurableEquiv
#print axioms Graphon.MeasurePreserving.exists_common_coupling_maps
#print axioms Graphon.cutNormDiff_pullback_le
#print axioms Graphon.MeasurePreserving.exists_controlled_cell_alignment
#print axioms Graphon.exists_mpEquiv_cutNormDiff_lt_add
#print axioms Graphon.cutDistance_triangle
#print axioms Graphon.totallyBounded
#print axioms Graphon.complete
#print axioms Graphon.compact
#print axioms Graphon.first_sampling_lemma
#print axioms Graphon.cutDistance_zero_of_homDensity_eq
#print axioms Graphon.homDensity_eq_sum_sampleMass
#print axioms Graphon.sampleMass_map_perm
#print axioms Graphon.samplePMF_map_comap
#print axioms Graphon.sampleLaw_map_comap
#print axioms Graphon.sampleLaw_const_eq_binomial
#print axioms GraphonSpace.mk_eq_mk_iff
#print axioms GraphonSpace.instCompactSpace
#print axioms Graphon.samplePMF_eq_all_iff_weaklyIsomorphic
#print axioms GraphonSpace.isClosedEmbedding_sampleCoordinates
#print axioms GraphonSpace.mixturePMF_map_comap
#print axioms GraphonSpace.continuous_mixturePMF_apply_toReal
#print axioms GraphonSpace.exists_subseq_tendsto
#print axioms Graphon.homDensity_sum
#print axioms GraphonSpace.mixtureExchangeableLaw_injective
#print axioms Graphon.sampleMass_ofSimpleGraphOn
#print axioms GraphonSpace.abs_integral_homDensityCoord_empiricalMixing_sub_le
#print axioms GraphonSpace.exists_mixtureExchangeableLaw_eq
#print axioms GraphonSpace.graphon_mixture_representation
#print axioms GraphonSpace.isDissociated_mixtureExchangeableLaw_iff
#print axioms GraphonSpace.isDissociated_iff_exists_sampleExchangeableLaw
#print axioms GraphonSpace.empiricalMixing_tendsto_representingMeasure
#print axioms GraphonSpace.abs_mixturePMF_empiricalMixing_sub_le
#print axioms InfiniteGraph.probabilityMeasure_ext_of_map_restrictFin
#print axioms Graphon.ExchangeableGraphLaw.infiniteLaw_map_restrictFin
#print axioms Graphon.ExchangeableGraphLaw.infiniteLaw_map_relabel
#print axioms Graphon.exchangeableGraphLawEquivInfinite
#print axioms GraphonSpace.infiniteMixtureLawEquiv
#print axioms GraphonSpace.isClosedEmbedding_infiniteSampleLaw
#print axioms GraphonSpace.empiricalGraphon_law_tendsto
#print axioms GraphonSpace.isDissociated_iff_exists_infiniteSampleExchangeableLaw
#print axioms InfiniteGraph.map_sampleInfinite_restrictFin
#print axioms InfiniteGraph.map_sampleInfinite
#print axioms GraphonSpace.mixtureInfiniteLaw_eq
#print axioms InfiniteGraph.sampledEmpiricalGraphon_tendstoInMeasure
#print axioms ProbabilityTheory.hasSubgaussianMGF_of_bounded_differences
#print axioms ProbabilityTheory.hasSubgaussianMGF_of_bounded_differences'
#print axioms Graphon.measureReal_abs_homDensity_sampled_sub_le
#print axioms InfiniteGraph.tsum_samplerSource_homDensity_tail_ne_top
#print axioms InfiniteGraph.sampledEmpiricalGraphon_tendsto_ae
#print axioms GraphonSpace.ae_tendsto_empiricalGraphon_infiniteSampleLaw
#print axioms GraphonSpace.map_limitGraphon_law
#print axioms InfiniteGraph.isDissociated_iff_exists_sampler
